/* Copyright 2026 Johan Denoyer F4WAT
 * https://github.com/jdenoy
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 *     Unless required by applicable law or agreed to in writing, software
 *     distributed under the License is distributed on an "AS IS" BASIS,
 *     WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *     See the License for the specific language governing permissions and
 *     limitations under the License.
 */

/*
 * EPIRB 406 (RX only) - decodes first-generation Cospas-Sarsat 406 MHz beacon
 * messages on the radio. Tune the VFO (FM, wide; 406.031 MHz covers the
 * 406.025-406.040 channels, or a test generator's frequency), then launch.
 *
 * The receiver is switched to RAW (RX HPF300 / LPF3K / de-emphasis and AFC off)
 * and the RX audio is left on: it reaches PA4 (the voice DAC pin, unused while
 * voice is disabled), held at mid-scale by the MCU DAC (unbuffered) and sampled
 * on ADC channel 4 at 9.6 kHz, timed from
 * SysTick, from the moment RSSI shows a burst. Samples go straight into dec406
 * (see README.md); the last five decoded messages stay in RAM.
 *
 * Keys (UV-K5 and UV-K1): UP/DOWN scroll, then select the newer / older message
 *   at an end · * normal / compact view · 4/6 tune -/+5 kHz (up to +/-50 kHz)
 *   · 5 back to the VFO frequency · 1 speaker on/off · MENU clear · EXIT quit.
 * The loader re-runs RADIO_SetupRegisters on exit; the app restores the ADC,
 * PA4, the DAC and its clock itself.
 * Screen texts and protocol names are read-only assets (gen_assets.py, API
 * level 2), kept out of the 4 KiB overlay.
 */

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>
#include "../app_api.h"
#include "epirb406_assets.h"   /* generated by gen_assets.py */
#include "dec406.c"

/* ---- MCU registers (PY32F071, core and SysTick at 48 MHz, 10 ms period) ---- */
#define SYST_LOAD   (*(volatile uint32_t *)0xE000E014u)
#define SYST_VAL    (*(volatile uint32_t *)0xE000E018u)
#define ADC_SR      (*(volatile uint32_t *)0x40012400u)
#define ADC_CR2     (*(volatile uint32_t *)0x40012408u)
#define ADC_SMPR3   (*(volatile uint32_t *)0x40012414u)
#define ADC_SQR3    (*(volatile uint32_t *)0x40012438u)
#define ADC_DR      (*(volatile uint32_t *)0x40012450u)
#define GPIOA_MODER (*(volatile uint32_t *)0x50000000u)
#define DAC_CR      (*(volatile uint32_t *)0x40007400u)
#define DAC_SWTRIGR (*(volatile uint32_t *)0x40007404u)
#define DAC_DHR12R1 (*(volatile uint32_t *)0x40007408u)
#define RCC_APBENR1 (*(volatile uint32_t *)0x4002103Cu)
#define RCC_DACEN   (1u << 29)
/* DAC channel 1 on, output buffer off, software trigger (TSEL1 = 111) */
#define DAC_CR_BIAS ((1u << 0) | (1u << 1) | (1u << 2) | (7u << 3))
#define BIAS_CODE   2048u
#define ADC_SR_EOC     (1u << 1)
#define ADC_CR2_START  ((1u << 22) | (1u << 20))   /* SWSTART | EXTTRIG */
#define SMP8_POS       24u
#define SMP4_POS       12u
#define ADC_CH_PA4     4u
#define CYC_PER_SAMPLE (48000000u / DEC406_FS)     /* 5000 */
#define CAP_MAX_CYC    (48000000u / 1000u * 900u)  /* 900 ms after trigger */

/* ---- BK4829 RAW receive ---- */
#define REG_2B      0x2B
#define REG_73      0x73
#define REG_30      0x30   /* 0 then back: VCO recalibration, relock on the new frequency */
#define REG_38      0x38   /* RX frequency, 10 Hz units, low 16 bits  */
#define REG_39      0x39   /* RX frequency, high 16 bits              */
#define STEP_10HZ   500    /* 5 kHz                                   */
#define OFF_MAX     10     /* +/- 10 steps = +/- 50 kHz               */

#define TRIG_DB     10
#define REARM_DB    5
#define COOL_MS     1500
#define TICK_MS     50
#define KEY_POLL_START_CYC (48000000u / 1000u * 300u)
#define KEY_POLL_CYC       (48000000u / 1000u * TICK_MS)
#define HISTORY     5u
#define CAPS_END    127u
#define SCROLL_X    72u
#define SPK_X       59u
#define VIEW_COMPACT 1u
#define BODY_BOTTOM 39u

typedef struct {
    dec406_info_t info;
    int16_t rssi;
    uint16_t seq;
} frame_t;

typedef struct {
    uint32_t sqr3, smpr3, moder, dac, rcc, dhr;
} saved_hw_t;

typedef struct {
    uint8_t spk, view;                  /* persistent byte order */
} app_cfg_t;
_Static_assert(sizeof(app_cfg_t)==2u && offsetof(app_cfg_t,view)==1u,
               "EPIRB config layout changed");

/* The app state in one struct: a function loads one base address instead of one
 * literal-pool word per global. Frequently used fields stay close to that base
 * for the Thumb load/store immediate ranges. The loader zeroes the overlay
 * (.bss) at every launch. */
static struct {
    const app_api_t *A;
    frame_t **history;                  /* newest first; records live on app_main's stack */
    uint32_t vfoFreq;                  /* VFO RX frequency at launch, 10 Hz units  */
    int32_t  floorQ;                   /* noise floor, dBm x64                     */
    uint32_t coolUntil;                /* wall-clock deadline for RSSI rearming    */
    uint8_t  count, cur, prevKey, lastErr;
    app_cfg_t cfg;
    int8_t   offSteps;                 /* tuning offset from the VFO, 5 kHz steps  */
    bool     running;
    int16_t  rssi;                     /* current RSSI                             */
    uint16_t vrow, top, lim, nSync, nFail; /* UI and counters */
} g;

/* ---- formatting ---- */
static char *put(char *o,const char *s){ while(*s)*o++=*s++; return o; }
/* Formatting by repeated subtraction: no division, so no __udivsi3 in the
 * 4 KiB overlay. Values printed stay below 100000. */
static uint8_t sub(uint32_t *v,uint32_t d){ uint8_t q=0; while(*v>=d){ *v-=d; q++; } return q; }
static char *puti(char *o,int32_t v){
    static const uint16_t P10[]={10000u,1000u,100u,10u,1u};
    uint32_t u;
    if(v<0){*o++='-';u=(uint32_t)(-v);} else u=(uint32_t)v;
    bool lead=false;
    for(uint8_t i=0;i<5;i++){
        uint8_t c=sub(&u,P10[i]);
        if(c||lead||i==4u){ *o++=(char)('0'+c); lead=true; }
    }
    return o;
}
/* Arc seconds to truncated decimal degrees followed by the hemisphere. */
static char *putPos(char *o,int32_t s,char pos,char neg){
    uint32_t a=(uint32_t)(s<0?-s:s);
    o=puti(o,sub(&a,3600u)); *o++='.';
    for(uint8_t k=0;k<5u;k++){ a*=10u; *o++=(char)('0'+sub(&a,3600u)); }
    *o++= s<0?neg:pos;
    return o;
}
static char *putFlags(char *o,const dec406_info_t *in,const char *s){
    bool source=in->longMsg&&in->stdLoc&&in->bch2;
    bool coarse=in->hasPos&&!in->hasFine;
    if(!(source||coarse||in->idRaw)) return o;
    bool have=false;
    if(source){ o=put(o,(in->internalPos?s+T_INT:s+T_EXT)+1); have=true; if(in->homing) o=put(o,s+T_HOMING); }
    if(coarse){ o=put(o,s+T_COARSE+(have?0:1)); have=true; }
    if(in->idRaw) o=put(o,s+T_RAWID+(have?0:1));
    return o;
}
static void tiny(char *buf,uint8_t x,uint8_t y,char *end){ *end='\0'; g.A->print_tiny(buf,x,y,false,true); }

/* ---- tuning: offset the RX frequency from the VFO (restored by the loader on exit) ---- */
static void tune(void){
    uint32_t f=(uint32_t)((int32_t)g.vfoFreq+(int32_t)g.offSteps*STEP_10HZ);
    g.A->bk_write(REG_38,(uint16_t)(f&0xFFFFu));
    g.A->bk_write(REG_39,(uint16_t)(f>>16));
    uint16_t r30=g.A->bk_read(REG_30);
    g.A->bk_write(REG_30,0);
    g.A->bk_write(REG_30,r30);
}
/* "433.645" from 10 Hz units, rounded to the kHz, without division */
static char *putFreq(char *o,uint32_t f){
    uint16_t mhz=0;
    f+=50u;
    while(f>=100000u){ f-=100000u; mhz++; }
    o=puti(o,mhz); *o++='.';
    *o++=(char)('0'+sub(&f,10000u)); *o++=(char)('0'+sub(&f,1000u)); *o++=(char)('0'+sub(&f,100u));
    return o;
}

/* ---- PA4 bias: the pin has no DC reference of its own (AC-coupled audio), so
 * 9.6 kHz sampling dragged it to 0 V and clipped half the message (406 Lab scope).
 * The MCU DAC on PA4, output buffer off, at mid-scale, holds it at ~VDD/2.
 * Set for the whole run, restored on exit. ---- */
static void biasOn(const saved_hw_t *saved){
    GPIOA_MODER=saved->moder|(3u<<8);           /* PA4 analog                     */
    RCC_APBENR1=saved->rcc|RCC_DACEN;
    DAC_CR=DAC_CR_BIAS;
    DAC_DHR12R1=BIAS_CODE;
    DAC_SWTRIGR=1u;                           /* DHR -> DOR                     */
}
static void biasOff(const saved_hw_t *saved){ DAC_CR=saved->dac; DAC_DHR12R1=saved->dhr; RCC_APBENR1=saved->rcc; GPIOA_MODER=saved->moder; }

/* ---- ADC on PA4 (channel 4); channel 8 (battery) restored afterwards ---- */
static void adcSelPA4(const saved_hw_t *saved){
    ADC_SMPR3=(saved->smpr3&~(7u<<SMP4_POS))|(((saved->smpr3>>SMP8_POS)&7u)<<SMP4_POS);
    ADC_SQR3=(saved->sqr3&~0x1Fu)|ADC_CH_PA4;
}
static void adcRestore(const saved_hw_t *saved){ ADC_SQR3=saved->sqr3; ADC_SMPR3=saved->smpr3; }
static uint16_t adcRead(void){
    ADC_CR2|=ADC_CR2_START;
    for(uint16_t n=0; !(ADC_SR&ADC_SR_EOC) && n<2000u; n++){}
    return (uint16_t)(ADC_DR&0x0FFFu);
}

/* ---- one burst: sample PA4 at 9.6 kHz into the decoder ---- */
static uint8_t capture(const saved_hw_t *saved){
    dec406_t d;
    dec406_init(&d,true);        /* INT: integrate the discriminator pulses */
    adcSelPA4(saved);
    uint32_t prev=SYST_VAL, cyc=0;
    uint32_t next=0;
    uint32_t nextKey=KEY_POLL_START_CYC;
    bool done=false;
    while(next<CAP_MAX_CYC){
        uint32_t v;
        do {
            v=SYST_VAL;
            cyc+=(v<=prev)?prev-v:prev+(SYST_LOAD+1u-v);
            prev=v;
        } while(cyc<next);
        if(dec406_push(&d,adcRead())){ done=true; break; }
        if(d.state==DEC406_SEARCH && cyc>=nextKey){
            nextKey+=KEY_POLL_CYC;
            uint8_t key=g.A->get_key();
            if(key<APP_KEY_INVALID){ adcRestore(saved); return key; }
        }
        next+=CYC_PER_SAMPLE;
    }
    adcRestore(saved);

    if(!done){ g.nFail++; g.lastErr=d.state==DEC406_DATA?2u:1u; return APP_KEY_INVALID; }
    g.nSync++; g.lastErr=0;
    frame_t *f=g.history[HISTORY-1u];
    for(uint8_t k=HISTORY-1u;k;k--) g.history[k]=g.history[k-1u];
    g.history[0]=f;
    dec406_parse(&d,&f->info);
    f->rssi=g.rssi;              /* RSSI at the trigger (not updated while sampling) */
    f->seq=g.nSync;
    if(g.count<HISTORY) g.count++;
    g.cur=0;
    g.top=0;
    return APP_KEY_INVALID;
}

/* ---- display ---- */
/* Render one row on scratch page 6, then shift each column into at most two
 * framebuffer pages. The fixed ID and diagnostic rows are redrawn afterwards. */
static void emit(char *buf,char *end){
    const app_api_t *A=g.A;
    *end='\0';
    unsigned y=(unsigned)g.vrow-g.top;
    if(y<BODY_BOTTOM){
        uint8_t *scratch=A->fb[6];
        if(g.cfg.view) A->print_tiny(buf,0,48,false,true);
        else A->print_normal(buf,0,0,6);
        unsigned page=y>>3, shift=y&7u;
        for(unsigned x=0;x<128u;x++){
            uint16_t bits=(uint16_t)scratch[x]<<shift;
            uint8_t *out=A->fb[page]+x;
            if(page==4u) bits&=0x7Fu;  /* y = 39 stays blank */
            *out|=(uint8_t)bits;
            if(page<4u) out[128]|=(uint8_t)(bits>>8);
            scratch[x]=0;
        }
    }
    g.vrow+=g.cfg.view?6u:8u;
}

static void draw(void){
    /* The UI texts live in the assets: one read per frame into this word-aligned
     * stack block, so each text costs a 2-byte sp-relative add instead of a
     * literal and its pool word (gen_assets.py keeps every offset aligned). */
    char s[UI_SIZE] __attribute__((aligned(4)));
    char str[34];
    char *o;
    g.A->asset_read(0,s,UI_SIZE);
    g.A->display_clear();
    g.A->status_clear();
    g.A->print_inverse(s+T_TITLE,2,0,true,true,(uint8_t)(2u+T_TITLE_CHARS*4u));
    g.A->draw_battery();
    g.vrow=8;

    if(!g.count && (g.A->ticks_ms()&512u)){
        g.vrow+=8u;
        o=put(str,s+T_WAIT);
        emit(str,o);
    }

    if(g.count){
        const frame_t *frame=g.history[g.cur];
        const dec406_info_t *in=&frame->info;

        /* Normal view has five or six rows, plus one when coordinates wrap.
         * Compact view has four or five rows depending on metadata. */
        o=puti(str,in->country); *o++=' ';
        uint8_t n=in->userProto ? (uint8_t)(16u+(in->proto&7u)) : (uint8_t)(in->proto&15u);
        o+=g.A->asset_read((uint16_t)(T_PROTO+n*T_PROTO_STRIDE),o,T_PROTO_STRIDE);
        emit(str,o);

        if(in->hasPos){
            char *latEnd=putPos(str,in->latS,'N','S');
            o=latEnd; *o++=' ';
            o=putPos(o,in->lonS,'E','W');
            if(!g.cfg.view && (unsigned)(o-str)>18u){
                emit(str,latEnd);
                o=putPos(str,in->lonS,'E','W');
            }
        } else o=put(str,s+T_NOPOS);
        emit(str,o);

        o=str;
        if(in->selftest) o=put(o,s+T_SELFTEST);
        o=put(o,in->longMsg?s+T_LONG:s+T_SHORT);
        if(!g.cfg.view){ emit(str,o); o=str; }
        else *o++=' ';
        o=put(o,s+T_BCH); o=put(o,in->bch1?s+T_OK:s+T_ERR); o=put(o,s+T_SEP);
        o=put(o,in->longMsg?(in->bch2?s+T_OK:s+T_ERR):s+T_NA);
        emit(str,o);

        o=putFlags(str,in,s);
        if(o!=str) emit(str,o);

        o=put(str,s+T_FRAME); o=puti(o,frame->seq); *o++=' '; o=puti(o,frame->rssi); o=put(o,s+T_DBM);
        emit(str,o);

        /* Keep the last row whole above the two fixed information rows. */
        g.lim=g.vrow>40u?g.vrow-40u:0u;

        /* Fixed ID over the scrolled rows; the tiny history capsule fits in
         * the remaining columns at its right. */
        for(unsigned x=0;x<128u;x++) g.A->fb[0][x]=0;
        g.A->print_bold(in->id,0,0,0);
        if(g.count>1u){
            o=str; *o++=(char)('1'+g.cur); *o++='/'; *o++=(char)('0'+g.count); *o='\0';
            g.A->print_inverse(str,CAPS_END-12u,0,false,true,CAPS_END);
        }
    }

    if(!g.count) g.lim=0;

    unsigned marks=0;
    if(g.top||g.cur) marks|=1u;
    if(g.top<g.lim||g.cur+1u<g.count) marks|=2u;
    if(g.cfg.spk) g.A->asset_read(BMP_SPK,g.A->status_line+SPK_X,SPK_W);
    g.A->asset_read((uint16_t)(BMP_SCROLL+marks*SCROLL_W),g.A->status_line+SCROLL_X,SCROLL_W);

    /* APRS-style dotted separator at y=40, above the two fixed information rows. */
    for(unsigned x=0;x<128u;x+=2u) g.A->fb[5][x]|=0x01u;

    o=str; *o++='R'; *o++='X'; *o++=' ';
    o=putFreq(o,g.vfoFreq+(uint32_t)((int32_t)g.offSteps*STEP_10HZ));
    if(g.offSteps){ *o++=' '; if(g.offSteps>0) *o++='+'; o=puti(o,(int32_t)g.offSteps*5); o=put(o,s+T_KHZ); }
    tiny(str,0,43,o);

    o=puti(str,g.rssi); o=put(o,s+T_SEP); o=puti(o,g.floorQ/64); o=put(o,s+T_DBM);
    tiny(str,(uint8_t)(128u-(unsigned)(o-str)*4u),43,o);

    o=put(str,s+T_FRAME); o=puti(o,g.nSync);
    o=put(o,s+T_ERROR); o=puti(o,g.nFail);
    if(g.lastErr) o=put(o,g.lastErr==1u?s+T_NOSYNC:s+T_CUT);
    tiny(str,0,49,o);
}

/* ---- input ---- */
static void handleKey(uint8_t key){
    int d=g.A->nav_dir(key);
    unsigned top=(unsigned)(g.top+d);
    if(top<=g.lim) g.top=(uint16_t)top;
    else if(key!=g.prevKey && (unsigned)(g.cur+d)<g.count){ g.cur=(uint8_t)(g.cur+d); g.top=0; }
    if(key==APP_KEY_INVALID||key==g.prevKey){ g.prevKey=key; return; }
    g.prevKey=key;
    switch(key){
        case APP_KEY_EXIT: g.running=false; break;
        case APP_KEY_1:    g.cfg.spk^=1u; g.A->audio_path(g.cfg.spk); break;
        case APP_KEY_STAR: g.cfg.view^=VIEW_COMPACT; g.top=0; break;
        case APP_KEY_5:    g.offSteps=0; tune(); break;
        case APP_KEY_MENU: g.count=g.cur=0; g.top=g.lim=0; g.nSync=g.nFail=0; g.lastErr=0; break;
        case APP_KEY_4:
        case APP_KEY_6: {
            int8_t n=(int8_t)(g.offSteps+(key==APP_KEY_4?-1:1));
            if(n>=-OFF_MAX && n<=OFF_MAX){ g.offSteps=n; tune(); }
            break; }
        default: break;
    }
}

__attribute__((section(".text.entry"),used))
void app_main(const app_api_t *api){
    frame_t frames[HISTORY];    /* on the stack: the 4 KiB overlay also holds .bss */
    frame_t *history[HISTORY];
    saved_hw_t saved;
    for(uint8_t k=0;k<HISTORY;k++) history[k]=&frames[k];
    g.A=api;
    g.history=history;
    g.prevKey=APP_KEY_INVALID;   /* the rest of g starts at 0 (overlay zeroed by the loader) */

    saved.sqr3=ADC_SQR3; saved.smpr3=ADC_SMPR3; saved.moder=GPIOA_MODER; saved.dac=DAC_CR;
    saved.rcc=RCC_APBENR1; saved.dhr=DAC_DHR12R1;
    biasOn(&saved);
    g.A->backlight_on();
    g.vfoFreq=g.A->rx_freq();
    g.A->bk_write(REG_2B,(uint16_t)((g.A->bk_read(REG_2B)|0x0700u)&~0x0007u));
    g.A->bk_write(REG_73,(uint16_t)(g.A->bk_read(REG_73)|0x0010u));
    g.A->cfg_load(&g.cfg.spk,sizeof g.cfg);
    g.cfg.spk=(uint8_t)(g.cfg.spk==1u);         /* erased flash or junk: speaker off */
    if(g.cfg.view!=VIEW_COMPACT) g.cfg.view=0;  /* normal view by default */
    g.A->audio_path(g.cfg.spk);                 /* PA4 is before the speaker amplifier */
    g.A->set_af(APP_AF_FM);
    g.A->delay_ms(50);

    int32_t f=0;
    for(uint8_t i=0;i<16;i++){ f+=g.A->rssi_dbm(); g.A->delay_ms(5); }
    g.floorQ=f*4;

    g.running=true;
    while(g.running){
        uint8_t key=APP_KEY_INVALID;
        for(uint8_t i=0;i<TICK_MS;i++){
            g.rssi=g.A->rssi_dbm();
            if(g.coolUntil){
                uint32_t now=g.A->ticks_ms();
                if(g.rssi < g.floorQ/64+REARM_DB || (int32_t)(now-g.coolUntil)>=0)
                    g.coolUntil=0;
                else { g.A->delay_ms(1); continue; }
            }
            if(g.rssi>=g.floorQ/64+TRIG_DB){
                key=capture(&saved);
                g.coolUntil=g.A->ticks_ms()+COOL_MS;
                if(!g.coolUntil) g.coolUntil=1u;
                break;
            }
            g.floorQ+=((int32_t)g.rssi*64-g.floorQ)/64;
            g.A->delay_ms(1);
        }
        if(key==APP_KEY_INVALID) key=g.A->get_key();
        handleKey(key);
        if(!g.running) break;
        draw();
        g.A->blit_status();
        g.A->blit_full();
        g.A->battery_sample();
        g.A->backlight_on();         /* keep the screen lit while waiting for bursts (and after a key) */
    }

    biasOff(&saved);             /* the ADC is already restored after each capture */
    g.A->set_af(APP_AF_MUTE);
    g.A->audio_path(false);
    g.A->cfg_save(&g.cfg.spk,sizeof g.cfg);
}
