/* Copyright 2026 Armel F4HWN
 * https://github.com/armel
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 *     Unless required by applicable law or agreed to in writing, software
 *     distributed under the License is distributed on an "AS IS" BASIS,
 *     WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *     See the License for the specific language governing permissions and
 *     limitations under the License.
 */

/*
 * SSTV receiver (RX-only) - receives pictures in 14 SSTV modes: Robot 36
 * and 72, Martin M1 and M2, Scottie S1, S2 and DX, PD50, PD90, PD120, PD160,
 * PD180, PD240 and PD290 (the ISS sends PD120 or PD180). No VIS at all: the
 * mode is picked with key 1, and key 5 starts one picture (and stops it).
 *
 * The modes are records in the assets (test/modes.py, after the Dayton paper):
 * for the RX the offsets of its picture scans from the sync end, their weights
 * in the luminance, the period and the pixel step.
 *
 * RX: the RX audio is sampled as APRS RX and EPIRB 406 do (PA4, ADC channel 4,
 * 9.6 kHz, continuously), through the receiver modelled and tested in
 * test/model.py (keep the two in step): band-pass, then the ratio of the sums
 * p = y1 (y0 + y2) and q = y1^2 is 2 cos w for a tone of angular step w,
 * whatever its level. Smoothed, it flags the sync; summed over a pixel, it
 * gives the luminance. Each period starts at its sync end (searched +-10 ms
 * around the prediction, the period tracked for the sender's clock); a period
 * without a sync keeps going on the prediction (no reset), and the luminance of
 * its scans (Y, or G B R weighted 2:1:1) goes to a line buffer, periods are
 * averaged per screen row, rendered 1-bit (threshold) or dithered (4x4 Bayer),
 * key 2. The chroma is ignored: grey. The picture fills the whole screen,
 * status line included; the keys and the row just drawn (one LCD page, ~1.5 ms)
 * are served after each period's last scan, before its sync ends. A small
 * bottom-right capsule shows RUN / LOST / OK while a picture is on screen.
 *
 * Keys (UV-K5 and UV-K1): 1 next decode mode, F then 1 the previous one ·
 *   2 rendering 1-bit / dither · 3 speaker on/off (off at launch: the decoder
 *   does not need it) · 4 picture / info screen (once a picture came) ·
 *   5 start one picture / stop · EXIT quit from the info screen (abort a
 *   picture being received, leave the picture view first). One picture is
 *   decoded per key-5 press: a sync loss is ridden out to the end, and the next
 *   picture needs another press. Decode mode, rendering and speaker are saved.
 * The loader re-runs RADIO_SetupRegisters on exit; the app restores the ADC,
 * PA4, the DAC and its clock itself.
 */

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>
#include "../app_api.h"
#include "sstv_assets.h"       /* generated by gen_assets.py */

/* ---- MCU registers (PY32F071, core and SysTick at 48 MHz, 10 ms period) ----
 * The ADC and DAC registers are reached from one base per block: the base goes
 * through an empty asm, so GCC addresses them as [base, #offset] from one
 * literal-pool word instead of one word per register address. */
static inline volatile uint32_t *hw(uint32_t a){
    volatile uint32_t *p=(volatile uint32_t *)a;
    __asm__("" : "+l"(p));
    return p;
}
#define SYST_LOAD   479999u    /* SysTick reload: 10 ms at 48 MHz */
#define SYST_VAL    (*(volatile uint32_t *)0xE000E018u)
#define ADC_SR      (hw(0x40012400u)[0x00/4])
#define ADC_CR2     (hw(0x40012400u)[0x08/4])
#define ADC_SMPR3   (hw(0x40012400u)[0x14/4])
#define ADC_SQR3    (hw(0x40012400u)[0x38/4])
#define ADC_DR      (hw(0x40012400u)[0x50/4])
#define GPIOA_MODER (*(volatile uint32_t *)0x50000000u)
#define DAC_CR      (hw(0x40007400u)[0x00/4])
#define DAC_SWTRIGR (hw(0x40007400u)[0x04/4])
#define DAC_DHR12R1 (hw(0x40007400u)[0x08/4])
#define RCC_APBENR1 (*(volatile uint32_t *)0x4002103Cu)
#define RCC_DACEN   (1u << 29)
/* DAC channel 1 on, output buffer off, software trigger (TSEL1 = 111) */
#define DAC_CR_BIAS ((1u << 0) | (1u << 1) | (1u << 2) | (7u << 3))
#define BIAS_CODE   2048u
#define ADC_SR_EOC     (1u << 1)
#define ADC_CR2_START  ((1u << 22) | (1u << 20))   /* SWSTART | EXTTRIG */
#define SMP8_POS       24u
#define SMP4_POS       12u
#define ADC_CH_PA4     4u
#define FS             9600u
#define CYC_PER_SAMPLE (48000000u / FS)            /* 5000 */
#define HOUSE_EVERY    480u    /* samples between key/screen slots (50 ms)       */
#define REFRESH_MS     5000u   /* periodic redraw of the info screen (battery)   */

/* ---- receiver (test/model.py, samples at 9.6 kHz) ---- */
#define BP_B0       21424  /* APRS RX's band-pass, Q14, 4x its gain           */
#define BP_A1     (-10714)
#define BP_A2       5673
#define SYNC_WIN    96     /* +-10 ms around the prediction                   */
#define MISS_MAX    20u    /* periods without a sync: the indicator says lost */
#define IND_OK_MS   1500u  /* the OK indicator stays this long                */

/* ---- a mode (test/modes.py record(), the MODES assets) ---- */
enum { SEG_SCAN = 0, SEG_ALT = 1 };    /* else a segment code is a REG_71 value */
typedef struct {                       /* what the receiver keeps (g.m) */
    uint8_t  vis;                      /* VIS byte, even parity in bit 7 */
    uint8_t  rowA, rowB;               /* screen rows: racc += A, a row each time >= B */
    uint8_t  nscan, syncMin, nseg;     /* scans per period, shortest sync run, TX segments */
    uint8_t  w[3], pad;                /* scan weights in the luminance (sum 4) */
    uint16_t periods;
    int32_t  per0;                     /* period, samples Q4 */
    int32_t  stepNum;                  /* pixel step Q16 = stepNum / period */
    int32_t  first;                    /* start bit -> end of the first sync, samples */
    int32_t  off[3];                   /* sync end -> scans, samples at per0 */
} mrx_t;
typedef struct { uint32_t dur; uint16_t code, pad; } seg_t;   /* cycles, SEG_* or REG_71 */
typedef struct {
    mrx_t    rx;
    uint32_t pre;                      /* Scottie's sync after the VIS, cycles */
    seg_t    seg[SEG_MAX];             /* one period, from the TX side */
} mode_t;
_Static_assert(sizeof(mrx_t)==MODE_RX && sizeof(mode_t)==MODE_SIZE,
               "mode record: keep sstv_app.c and test/modes.py in step");

enum { H_IDLE = 0, H_FORCE, H_LINE };
/* info screen status: the order of ST_TEXT in gen_assets.py */
enum { ST_WAIT = 0, ST_RX, ST_OK, ST_LOST, ST_SENT, ST_DENIED, ST_ABORT, ST_NOPIC, ST_RXABORT };
/* picture-view indicator (bottom-right capsule) */
enum { IND_NONE = 0, IND_RUN, IND_LOST, IND_OK };

#define WAIT_CAPS_X 40u    /* "WAIT" capsule in the status bar, after the title (APRS RX) */
#define SPK_X       59u    /* speaker icon (FoxHunt's, x = 59-68) after the capsule (APRS RX) */
#define F_X         70u    /* F icon (9 px) while armed, as APRS TX / FoxHunt     */

/* The app state in one struct: a function loads one base address instead of one
 * literal-pool word per global. Bytes, then halfwords, then words, so every
 * field stays within the Thumb load/store immediate ranges (ldrb <= 31, ldrh <= 62,
 * ldr <= 124); the mode and the registers saved for the exit go last.
 * The loader zeroes the overlay (.bss) at every launch. */
static struct {
    uint8_t  prevKey, redraw, spk;
    uint8_t  image, have, mode;        /* picture view on, a picture came, 0 dither / 1 1-bit */
    uint8_t  rxSel, rxMode;            /* chosen mode; rxMode MODE_COUNT: none yet */
    uint8_t  st, status, lineDone, dirty; /* receiver state, info status, house after this
                                          sample, picture page to show + 1 */
    uint8_t  clr;                      /* picture pages shown since the start (one per period) */
    uint8_t  ind, indDirty;            /* bottom-right indicator, and it needs a redraw */
    uint8_t  row, racc, cnt;           /* screen row, period->row accumulator, periods in row */
    uint8_t  px, sc, found, prevFound, miss; /* pixel, scan, this/last period's sync found,
                                          periods without */
    uint8_t  fArm, force;              /* fArm: F pressed; force: a picture is being received */
    bool     running;
    uint16_t hc;                       /* samples since the last key/screen slot */
    uint16_t line;                     /* period of the picture                     */
    const app_api_t *A;
    uint8_t  *img;                     /* the picture, LCD layout (app_main's stack) */
    uint16_t *acc;                     /* row sums of the luminance (stack)          */
    uint16_t *lbuf;                    /* the current period's luminance x 4 (stack) */
    int32_t  x1, x2, y1, y2, P, Q;     /* band-pass, smoothed p and q                */
    int32_t  sp, sq;                   /* p and q summed over the current pixel      */
    int32_t  n, srun;                  /* sample index, sync run */
    int32_t  c, pred, step, per;       /* period start, prediction, Q16 px step, period Q4 */
    int32_t  ys;                       /* start of the current scan                  */
    uint32_t next, tDraw, indT;        /* next sample (clkCyc), last redraw, OK stamp */
    mrx_t    m;                        /* the mode being received                    */
    uint32_t savedSqr3, savedSmpr3, savedModer, savedDac, savedRcc, savedDhr;
} g;
static char str[34];

/* ---- tiny freestanding helpers: GCC may turn the zeroing / copy loops into calls ---- */
void *memset(void *d, int c, size_t n) {
    uint8_t *p = d; while (n--) *p++ = (uint8_t)c; return d;
}
void *memcpy(void *d, const void *s, size_t n) {
    uint8_t *p = d; const uint8_t *q = s; while (n--) *p++ = *q++; return d;
}

/* Division through the resident helper (API level 2) instead of libgcc's: the
 * period and the luminance divide, signed only. */
__attribute__((noinline))
uint64_t __aeabi_idivmod(int32_t n, int32_t d){ return g.A->idivmod(n, d); }
uint64_t __aeabi_idiv(int32_t n, int32_t d) __attribute__((alias("__aeabi_idivmod")));

/* ---- formatting ---- */
__attribute__((noinline))
static char *put(char *o,const char *s){ while(*s)*o++=*s++; return o; }
/* Formatting by repeated subtraction: no division. Values printed stay below 100000. */
static uint8_t sub(uint32_t *v,uint32_t d){ uint8_t q=0; while(*v>=d){ *v-=d; q++; } return q; }
static const uint16_t P10[]={10000u,1000u,100u,10u,1u};
static char *puti(char *o,uint32_t u){
    bool lead=false;
    for(unsigned i=0;i<5u;i++){
        uint8_t c=sub(&u,P10[i]);
        if(c||lead||i==4u){ *o++=(char)('0'+c); lead=true; }
    }
    return o;
}

/* The frequency (10 Hz units) drawn as the main screen draws it (ui/main.c,
 * ENABLE_BIG_FREQ), as APRS RX: the big digits up to the kHz on lines 4-5, the
 * last two digits in the small font on line 5 right after them. */
static void drawFreq(uint32_t f){
    const app_api_t *A=g.A;
    uint16_t m=0;
    while(f>=100000u){ f-=100000u; m++; }
    char *o=puti(str,m);
    *o++='.';
    for(uint8_t i=0;i<5u;i++) *o++=(char)('0'+sub(&f,P10[i]));
    *o='\0';
    uint8_t n=(uint8_t)(o-str), big=(uint8_t)(n-3u);    /* digits before "00" */
    A->print_normal(str+n-2u,(uint8_t)(big*13u+3u),0,5);     /* "00"      */
    str[n-2u]='\0';
    A->display_freq(str,0,4,false);                          /* "144.800" */
}

/* ---- screens ---- */
/* A 3x5 capsule on line 0, in capitals: from x = 2 (as the title in the status
 * bar), or ending at x = 125. */
static void tag(const char *s,bool right){
    char *o=str;
    for(char ch; (ch=*s++)!='\0'; ) *o++=(char)(ch>='a'&&ch<='z'?ch-32:ch);
    *o='\0';
    uint8_t w=(uint8_t)((o-str)*4), x=right?(uint8_t)(125u-w):2u;
    g.A->print_inverse(str,x,0,false,true,(uint8_t)(x+w));
}
/* Info screen: the decode mode and rendering, the status (with the mode of
 * the picture), the RX frequency, the keys. */
static void draw(void){
    const app_api_t *A=g.A;
    /* The UI texts live in the assets: one read per frame into this word-aligned
     * stack block, so each text costs a 2-byte sp-relative add. */
    char s[UI_SIZE] __attribute__((aligned(4)));
    char nm[T_NAMES_STRIDE];
    uint8_t t;
    A->asset_read(0,s,UI_SIZE);
    A->display_clear();
    A->status_clear();
    A->print_inverse(s+T_TITLE,2,0,true,true,(uint8_t)(2u+T_TITLE_CHARS*4u));
    if(g.force) A->print_inverse(s+T_FORCE,24,0,true,true,(uint8_t)(24u+T_FORCE_CHARS*4u));
    if(g.spk) A->asset_read(BMP_SPK,A->status_line+SPK_X,BMP_SPK_LEN);
    if(g.fArm) A->asset_read(BMP_F,A->status_line+F_X,BMP_F_LEN);
    A->draw_battery();
    /* line 0: the decode mode (key 1) on the left, the rendering (key 2) on the
     * right, as 3x5 capsules */
    A->asset_read((uint16_t)(T_NAMES+g.rxSel*T_NAMES_STRIDE),nm,T_NAMES_STRIDE);
    tag(nm,false);
    tag(g.mode?s+T_1BIT:s+T_DITHER,true);
    if(!g.have)                         /* no picture yet: a capsule, as APRS RX */
        A->print_inverse(s+T_WAIT,WAIT_CAPS_X,0,true,true,(uint8_t)(WAIT_CAPS_X+T_WAIT_CHARS*4u));
    if(g.status!=ST_WAIT){              /* the capsule says it */
        char *o=str;
        if(g.status<=ST_LOST){          /* a picture: "PD120 123/248", "PD120 OK", "PD120 lost" */
            A->asset_read((uint16_t)(T_NAMES+g.rxMode*T_NAMES_STRIDE),nm,T_NAMES_STRIDE);
            o=put(o,nm);
        }
        A->asset_read((uint16_t)(ST_TEXT+g.status),&t,1);
        o=put(o,s+t);
        if(g.status==ST_RX){ o=puti(o,g.line); *o++='/'; o=puti(o,g.m.periods); }
        *o='\0';                        /* 18 characters at most: "Scottie DX 255/256" */
        A->print_normal(str,0,0,2);
    }
    drawFreq(A->rx_freq());
    A->print_tiny(s+T_HELP,0,49,false,true);
}
/* the bottom-right capsule of the picture view: RUN / LOST / OK */
static void overlayInd(unsigned pg){
    const app_api_t *A=g.A;
    const char *s;
    uint8_t n;
    if(pg!=7u) return;
    if(g.ind==IND_RUN){ s="RUN"; n=3u; }
    else if(g.ind==IND_LOST){ s="LOST"; n=4u; }
    else if(g.ind==IND_OK){ s="OK"; n=2u; }
    else return;
    uint8_t w=(uint8_t)(n*4u), x=(uint8_t)(125u-w);
    A->print_inverse(s,x,7,false,true,(uint8_t)(x+w));
}
/* The current view to the LCD: the picture (whole screen) or the info screen. */
static void show(void){
    const app_api_t *A=g.A;
    if(g.image){
        memcpy(A->status_line,g.img,128);
        memcpy(A->fb[0],g.img+128,896);
        overlayInd(7u);
        g.indDirty=0;
    } else draw();
    A->blit_status();
    A->blit_full();
}
/* One LCD page (0 the status line, 1-7 the frame buffer) to the LCD: ~1.5 ms. */
static void blitPage(unsigned pg){
    const app_api_t *A=g.A;
    if(pg) A->blit_line(pg-1u); else A->blit_status();
}
static uint8_t *page(unsigned pg){
    const app_api_t *A=g.A;
    return pg?A->fb[pg-1u]:A->status_line;
}

/* ---- absolute cycle clock: the 10 ms SysTick interrupt count (ticks_ms) plus
 * the position in the current period. A blocking service (a full LCD blit is
 * ~11 ms: SPI at 750 kHz) cannot lose a period, as a counter of SYST_VAL
 * differences would. Wraps every 89 s: compare with a signed difference. ---- */
static uint32_t clkCyc(void){
    const app_api_t *A=g.A;
    uint32_t t,v;
    do { t=A->ticks_ms(); v=SYST_VAL; } while(t!=A->ticks_ms());   /* no wrap in between */
    return t*48000u+(SYST_LOAD-v);
}

/* ---- PA4 bias: the pin has no DC reference of its own (AC-coupled audio); the
 * MCU DAC on PA4, output buffer off, at mid-scale, holds it at ~VDD/2.
 * Set for the whole run, restored on exit (see EPIRB 406). ---- */
static void biasOn(void){
    GPIOA_MODER=g.savedModer|(3u<<8);           /* PA4 analog                     */
    RCC_APBENR1=g.savedRcc|RCC_DACEN;
    DAC_CR=DAC_CR_BIAS;
    DAC_DHR12R1=BIAS_CODE;
    DAC_SWTRIGR=1u;                           /* DHR -> DOR                     */
}
static void biasOff(void){ DAC_CR=g.savedDac; DAC_DHR12R1=g.savedDhr; RCC_APBENR1=g.savedRcc; GPIOA_MODER=g.savedModer; }

/* ---- ADC on PA4 (channel 4); channel 8 (battery) restored afterwards ---- */
static void adcSelPA4(void){
    ADC_SMPR3=(g.savedSmpr3&~(7u<<SMP4_POS))|(((g.savedSmpr3>>SMP8_POS)&7u)<<SMP4_POS);
    ADC_SQR3=(g.savedSqr3&~0x1Fu)|ADC_CH_PA4;
}
static void adcRestore(void){ ADC_SQR3=g.savedSqr3; ADC_SMPR3=g.savedSmpr3; }
static uint16_t adcRead(void){
    ADC_CR2|=ADC_CR2_START;
    for(uint16_t n=0; !(ADC_SR&ADC_SR_EOC) && n<2000u; n++){}
    return (uint16_t)(ADC_DR&0x0FFFu);
}

/* ---- receiver state ---- */
static void idle(void){ g.st=H_IDLE; g.srun=0; }
/* key 5: arm the key-1 mode and wait for the next sync (H_FORCE) */
static void forceArm(void){
    g.A->asset_read((uint16_t)(MODES+g.rxSel*MODE_SIZE),&g.m,MODE_RX);
    g.st=H_FORCE; g.srun=0; g.miss=0; g.lineDone=0;
    g.status=ST_WAIT;
    g.ind=IND_NONE; g.indDirty=1;
    g.redraw=1;
}

/* ---- RX ---- */
/* the current scan from g.c, its offset scaled to the tracked period
 * (|per - per0| <= per0 / 16: no overflow) */
static void scanStart(void){
    int32_t o=g.m.off[g.sc];
    g.ys=g.c+o+o*(g.per-g.m.per0)/g.m.per0;
    g.px=0;
    g.sp=g.sq=0;
}
static void restart(void){              /* the period from g.c */
    g.step=g.m.stepNum/g.per;
    g.sc=0;
    memset(g.lbuf,0,128u*sizeof g.lbuf[0]);
    scanStart();
}
/* start a picture at the sync end the key-5 hunter just found */
static void startForcedAt(int32_t syncEnd){
    g.line=0;
    g.row=g.racc=g.cnt=0;
    memset(g.acc,0,128u*sizeof g.acc[0]);
    memset(g.img,0,1024);
    g.per=g.m.per0;
    g.miss=0;
    g.c=g.pred=syncEnd;
    g.found=1;
    g.prevFound=0;
    g.rxMode=g.rxSel;
    g.st=H_LINE;
    g.have=1;
    g.image=1;
    g.status=ST_RX;
    g.clr=0;
    g.ind=IND_RUN; g.indDirty=1;
    g.A->backlight_on();
    restart();
}
/* luminance 0..255 of a pixel: 285 - 256 P / Q (2300 Hz ~ 255, 1500 Hz ~ 0) */
static uint8_t lum(int32_t sp,int32_t sq){
    while(sq>=(1<<22)){ sp>>=1; sq>>=1; }
    int32_t v=285-sp*256/sq;
    return (uint8_t)(v<0?0:v>255?255:v);
}
/* a screen row from the sums of its cnt periods (x 4): 1 = dark under the threshold */
static void putRow(void){
    uint8_t t[4];
    unsigned r=g.row, cnt=(unsigned)g.cnt<<2;
    g.A->asset_read((uint16_t)(THR+g.mode*16u+(r&3u)*4u),t,4);
    uint8_t *p=g.img+(r>>3)*128u, m=(uint8_t)(1u<<(r&7u));
    uint16_t *a=g.acc;
    for(unsigned x=0;x<128u;x++){
        if(a[x]<t[x&3u]*cnt) p[x]|=m; else p[x]&=(uint8_t)~m;
        a[x]=0;
    }
    g.dirty=(uint8_t)((r>>3)+1u);
}
static void endLine(void){
    if(!g.found){                        /* no sync this period: ride it out */
        if(g.miss<255u) g.miss++;
        if(g.miss>MISS_MAX){ g.status=ST_LOST; if(g.ind!=IND_LOST){ g.ind=IND_LOST; g.indDirty=1; } }
    } else {
        g.miss=0;
        if(g.ind==IND_LOST){ g.ind=IND_RUN; g.indDirty=1; }
        if(g.status==ST_LOST) g.status=ST_RX;
    }
    uint16_t *a=g.acc, *l=g.lbuf;
    for(unsigned x=0;x<128u;x++) a[x]+=l[x];
    g.cnt++;
    g.racc+=g.m.rowA;
    if(g.racc>=g.m.rowB){ g.racc-=g.m.rowB; putRow(); g.cnt=0; g.row++; }
    if(++g.line>=g.m.periods){           /* one picture done: stop and keep it */
        g.status=ST_OK;
        g.ind=IND_OK; g.indT=g.A->ticks_ms(); g.indDirty=1;
        g.force=0;
        idle();
        return;
    }
    g.c=g.pred=g.c+(g.per>>4);
    g.prevFound=g.found;
    g.found=0;
    g.lineDone=1;                        /* keys and screen before the sync ends */
    restart();
}

static void sample(int32_t adc){
    int32_t x=adc-2048;
    int32_t y=(BP_B0*(x-g.x2)-BP_A1*g.y1-BP_A2*g.y2)>>14;
    int32_t y1=g.y1;
    int32_t p=y1*(y+g.y2), q=y1*y1;
    g.x2=g.x1; g.x1=x; g.y2=y1; g.y1=y;
    int32_t P=g.P+=(p-g.P)>>3;
    int32_t Q=g.Q+=(q-g.Q)>>3;
    bool sync=4*P>5*Q;                   /* below ~1360 Hz */
    int32_t n=g.n;

    if(g.st==H_IDLE){
        /* nothing to decode: key 5 arms a picture (forceArm) */
    } else if(g.st==H_FORCE){
        /* forced RX: the first horizontal sync (1200 Hz) is the period start */
        if(sync) g.srun++;
        else if(g.srun){
            int32_t ln=g.srun;
            g.srun=0;
            if(ln>=g.m.syncMin) startForcedAt(n);
        }
    } else {
        /* The sync end (1200 -> 1500 Hz) within +-10 ms of the prediction
         * (re)starts the period: the scans never read as a sync, and a late
         * sync restarts the line buffer before it reaches the picture. */
        if(sync) g.srun++;
        else if(g.srun){
            int32_t ln=g.srun;
            g.srun=0;
            if(ln<g.m.syncMin) goto scan;
            /* a sender with a fast clock: the next sync ends before this
             * period's last scan is over (or this period ran on the prediction
             * and missed its own sync); the period is cut short there, and the
             * keys wait for the next one (no time before the next scan) */
            int32_t e=n-(g.c+(g.per>>4));
            if(e>=-SYNC_WIN && e<=SYNC_WIN){
                endLine();
                g.lineDone=0;
                if(g.st!=H_LINE) return;
            }
            int32_t err=n-g.pred;
            if(!g.found && err>=-SYNC_WIN && err<=SYNC_WIN){
                if(g.prevFound){        /* the period, 1/8 of the error, +-6 % */
                    int32_t per=g.per+err*2, p0=g.m.per0, lim=p0>>4;
                    if(per>p0+lim) per=p0+lim;
                    if(per<p0-lim) per=p0-lim;
                    g.per=per;
                }
                g.c=n;
                g.found=1;
                g.miss=0;
                restart();
                return;
            }
        }
    scan:;
        int32_t d=n-g.ys;
        if(d>=0){
            unsigned k=(unsigned)((d*g.step)>>16);
            if(k!=g.px){
                g.lbuf[g.px]+=(uint16_t)(g.m.w[g.sc]*lum(g.sp,g.sq));
                g.sp=g.sq=0;
                g.px=(uint8_t)k;
                if(k>=128u){
                    if(++g.sc>=g.m.nscan) endLine(); else scanStart();
                    return;
                }
            }
            g.sp+=p;
            g.sq+=q;
        }
    }
}

/* ---- input ---- */
static void handleKeys(void){
    const app_api_t *A=g.A;
    uint8_t key=A->get_key();
    if(key==APP_KEY_INVALID||key==g.prevKey){ g.prevKey=key; return; }
    g.prevKey=key;
    g.redraw=1;
    A->backlight_on();
    if(key==APP_KEY_F){ g.fArm^=1u; return; }   /* as APRS TX: icon while armed */
    bool back=g.fArm;                    /* F then a key: it goes backwards */
    g.fArm=0;
    if(key==APP_KEY_EXIT){
        /* Abort a picture and go back to the info screen; what came so far
         * stays viewable (key 4). From the picture view: back to the info
         * screen. From the info screen: quit. */
        g.force=0;
        if(g.st==H_LINE||g.st==H_FORCE){ idle(); g.status=ST_RXABORT; g.image=0; }
        else if(g.image) g.image=0;
        else g.running=false;
    }
    else if(key==APP_KEY_1){             /* decode mode: next, F then 1 the previous */
        if(back) g.rxSel=(uint8_t)(g.rxSel?g.rxSel-1u:MODE_COUNT-1u);
        else if(++g.rxSel>=MODE_COUNT) g.rxSel=0;
        if(g.force) forceArm();          /* re-arm with the new mode */
    }
    else if(key==APP_KEY_2) g.mode^=1u;   /* rendering, from the next row on */
    else if(key==APP_KEY_3){ g.spk^=1u; A->audio_path(g.spk); }   /* speaker, as FoxHunt's audio */
    else if(key==APP_KEY_4){ if(g.have) g.image^=1u; else g.status=ST_NOPIC; }
    else if(key==APP_KEY_5){             /* start one picture / stop */
        if(g.force){ g.force=0; idle(); }
        else { g.force=1; forceArm(); }
    }
}
static void house(void){
    const app_api_t *A=g.A;
    handleKeys();
    if(!g.running) return;
    A->backlight_update();     /* normal BLTime timeout; keys re-arm it in get_key() */
    if(g.image && !g.redraw){  /* one page at most (~1.5 ms): a new row, else the
                                  next page not shown yet since the start */
        unsigned pg=8u;
        if(g.dirty) pg=g.dirty-1u;
        else if(g.st==H_LINE && g.clr<8u) pg=g.clr++;
        if(pg<8u){
            memcpy(page(pg),g.img+pg*128u,128);
            if(pg==7u){ overlayInd(7u); g.indDirty=0; }
            blitPage(pg);
        }
    }
    g.dirty=0;
    uint32_t t=A->ticks_ms();
    if(g.ind==IND_OK && (uint32_t)(t-g.indT)>=IND_OK_MS){ g.ind=IND_NONE; g.indDirty=1; }
    if(g.image && g.indDirty && !g.redraw){   /* the indicator changed: redraw the bottom page */
        g.indDirty=0;
        memcpy(page(7u),g.img+7u*128u,128);
        overlayInd(7u);
        blitPage(7u);
    }
    if(!g.image && t-g.tDraw>=REFRESH_MS) g.redraw=1;
    if(!g.redraw) return;
    g.redraw=0;
    g.tDraw=t;
    if(!g.image){              /* the battery is on ADC channel 8 */
        adcRestore();
        A->battery_sample();
        adcSelPA4();
    }
    show();
}

static void listen(void){
    g.next=clkCyc();
    while(g.running){
        while((int32_t)(clkCyc()-g.next)<0){}
        g.next+=CYC_PER_SAMPLE;
        g.n++;
        sample(adcRead());
        if(g.st==H_LINE){                /* inside a picture: after each period */
            if(!g.lineDone) continue;
            g.lineDone=0;
        } else {                         /* otherwise serve the keys every 50 ms */
            if(++g.hc<HOUSE_EVERY) continue;
            g.hc=0;
        }
        house();
        while((int32_t)(clkCyc()-g.next)>=0){ g.next+=CYC_PER_SAMPLE; g.n++; }  /* the slots it took */
    }
}

__attribute__((section(".text.entry"),used))
void app_main(const app_api_t *api){
    uint8_t img[1024];           /* on the stack: the 4 KiB overlay also holds .bss */
    uint16_t acc[128], lbuf[128];
    uint8_t c[3];
    g.A=api;
    g.img=img;
    g.acc=acc;
    g.lbuf=lbuf;
    g.prevKey=APP_KEY_INVALID;   /* the rest of g starts at 0 (overlay zeroed by the loader) */
    g.rxMode=MODE_COUNT;         /* no picture yet */

    g.savedSqr3=ADC_SQR3; g.savedSmpr3=ADC_SMPR3; g.savedModer=GPIOA_MODER; g.savedDac=DAC_CR;
    g.savedRcc=RCC_APBENR1; g.savedDhr=DAC_DHR12R1;
    biasOn();
    api->backlight_on();
    api->cfg_load(c,3);          /* rendering (erased 0xFF: 1-bit), decode mode, speaker */
    g.mode=c[0]?1u:0u;
    if(c[1]<MODE_COUNT) g.rxSel=c[1];
    g.spk=(uint8_t)(c[2]==1u);   /* erased (0xFF): off */
    /* Speaker amplifier (PA8) as saved, off by default: PA4 joins the audio
     * before the amplifier (APRS RX), so the decoder only needs the BK4829 AF
     * output. Key 3 toggles it. */
    api->audio_path(g.spk);
    api->set_af(APP_AF_FM);
    api->delay_ms(50);
    adcSelPA4();

    g.running=true;
    g.redraw=1;
    listen();

    adcRestore();
    biasOff();
    api->set_af(APP_AF_MUTE);
    api->audio_path(false);
    c[0]=g.mode; c[1]=g.rxSel; c[2]=g.spk;
    api->cfg_save(c,3);
}
