#ifndef BITMAP_MANGOSTEEN_H
#define BITMAP_MANGOSTEEN_H

#include <stdint.h>

#define BITMAP_MANGOSTEEN_WIDTH  48
#define BITMAP_MANGOSTEEN_HEIGHT 48
#define BITMAP_MANGOSTEEN_PAGES  (BITMAP_MANGOSTEEN_HEIGHT / 8)

extern const uint8_t BITMAP_Mangosteen[BITMAP_MANGOSTEEN_PAGES * BITMAP_MANGOSTEEN_WIDTH];

#endif
