/* Copyright 2026
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * LBJ RX (development build) - receives Chinese railway LBJ (POCSAG 1200 baud,
 * direct FSK, ~821.24 MHz) and shows the decoded LBJ-family messages (address
 * window 1233980..1234020; other POCSAG traffic is ignored). Reference:
 * Sdr-Is-Fun/RTL_SDR_LBJ_RECEIVER and APRS RX on this firmware.
 *
 * The BK4829 has no POCSAG/FM-data demodulator, so as EPIRB 406 / APRS RX do,
 * the RX audio reaches PA4 (voice DAC pin, held at mid-scale by the MCU DAC) and
 * is sampled on ADC channel 4 at 19.2 kHz (16 samples per 1200-baud bit), timed
 * from SysTick, continuously. The receiver is switched to RAW (RX HPF/LPF,
 * de-emphasis and AFC off): the de-emphasis would destroy the NRZ baseband.
 * Each sample goes through the model in test/model_rx.py: slow baseline tracker,
 * low-pass biquad, a one-bit matched-filter boxcar (weak-signal win), symmetric
 * peak tracker with hysteresis, DPLL (65536/bit), then POCSAG sync / batch /
 * BCH(31,21) single-bit correction and the LBJ BCD layout.
 *
 * Keys: UP/DOWN pick the newer/older record (one step per press, no auto-repeat);
 * 1 speaker; 2 clear; 4 backlight always-on / timeout; 5 Chinese/English; EXIT
 * quit. SUM-only for now. The bottom status bar (tiny font) shows the key-state
 * hints (5 language, 4 backlight, 1 speaker) then x/y (selected record / total,
 * 1 = newest) and the live RSSI (-xx dBm), refreshed every 0.5 s and drawn from
 * launch (0/0). The PDU page and the M/S/W/F/B counter row are kept under #if 0
 * (they overflowed the 4 KiB overlay); restore them together.
 *
 * For the new-generation LB alert the SUM page decodes the detail block:
 * 1234001/1234002 carry a standalone 30..64-char block, or a merged 65-char
 * report (15-char short prefix + 50-char block); 1233999/1234000 carry the
 * merged form. Inside the block, [0:4] is 2 ASCII prefix chars, [4:7] the
 * 3-digit model code, [7:12] the loco number, [12:14] the end flag, [14:30]
 * the GB2312 route, [30:39]/[39:47] the DDDMM.MMMM/DDMM.MMMM coordinates.
 * The coordinates are shown in decimal degrees; the train/speed/km come from
 * a merged report's own short prefix, or from the most recent 1233999/1234000
 * short report. A detail report and its 1233999/1234000 base alert stay as
 * separate history entries. The route and the model name use the radio's
 * built-in 8x8 Chinese font; key 5 switches to an ASCII fallback (English
 * abbreviations like DF4C/SS7E, route hidden) for radios without it.
 */

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>
#include "../app_api.h"
#include "lbj_assets.h"        /* generated by gen_assets.py */
#include "lbj_dec.h"
#include "lbj_dec.c"           /* the POCSAG/LBJ core (same translation unit) */

/* ---- MCU registers (PY32F071, core and SysTick at 48 MHz, 10 ms period) ---- */
static inline volatile uint32_t *hw(uint32_t a){
    volatile uint32_t *p=(volatile uint32_t *)a;
    __asm__("" : "+l"(p));
    return p;
}
#define SYST_LOAD   (*(volatile uint32_t *)0xE000E014u)
#define SYST_VAL    (*(volatile uint32_t *)0xE000E018u)
#define ADC_SR      (hw(0x40012400u)[0x00/4])
#define ADC_CR2     (hw(0x40012400u)[0x08/4])
#define ADC_SMPR3   (hw(0x40012400u)[0x14/4])
#define ADC_SQR3    (hw(0x40012400u)[0x38/4])
#define ADC_DR      (hw(0x40012400u)[0x50/4])
#define GPIOA_MODER (*(volatile uint32_t *)0x50000000u)
#define DAC_CR      (hw(0x40007400u)[0x00/4])
#define DAC_SWTRIGR (hw(0x40007400u)[0x04/4])
#define DAC_DHR12R1 (hw(0x40007400u)[0x08/4])
#define RCC_APBENR1 (*(volatile uint32_t *)0x4002103Cu)
#define RCC_DACEN   (1u << 29)
#define DAC_CR_BIAS ((1u << 0) | (1u << 1) | (1u << 2) | (7u << 3))
#define BIAS_CODE   2048u
#define ADC_SR_EOC     (1u << 1)
#define ADC_CR2_START  ((1u << 22) | (1u << 20))
#define SMP8_POS       24u
#define SMP4_POS       12u
#define ADC_CH_PA4     4u
#define FS             19200u
#define CYC_PER_SAMPLE (48000000u / FS)
#define HOUSE_EVERY    960u    /* samples between key/screen slots (50 ms) */
#define BUSY_MAX       100u    /* serve keys anyway after 5 s inside a message */

#define REG_2B  0x2Bu          /* RX HPF/LPF + de-emphasis + AFC (EPIRB 406 RAW) */
#define REG_73  0x73u

/* ---- demodulator (test/model_rx.py, class DemodInt; the C is a transcription) */
#define DC_SHIFT   7
#define PK_SHIFT   8
#define PLL_STEP   4096        /* 65536 per bit / 16 samples per bit */
#define PLL_SHIFT  3
#define INT_SHIFT  9
#define INT_MAX    82          /* ~ PLL_STEP * 0.02 */
#define BOX        16u         /* 1-bit matched filter (samples per bit) */
#define M_B0       725         /* low-pass biquad 1500 Hz @ 19.2 kHz, Q14 */
#define M_B1       1451
#define M_A1     (-21674)
#define M_A2       8192

typedef struct {
    int32_t dc;
    int32_t x1, x2, y1, y2;
    int32_t hi, lo;
    int32_t ph, iint;
    int32_t bsum;                  /* running sum of the last BOX samples */
    int16_t box[BOX];
    uint8_t last, bi;
} dem_t;

/* ---- decoded-message history ---- */
#define HISTORY   8u
#define BCDMAX    96u

typedef struct {
    uint32_t addr;
    uint8_t  func, flags, len;
    char     bcd[BCDMAX];
} rec_t;
#define RF_ERR  1u             /* BCH could not correct the report */
#define RF_LBJ  2u             /* address belongs to the LBJ set */

static struct {
    const app_api_t *A;
    rec_t **hist;              /* newest first; records live on app_main's stack */
    char   *text;              /* formatting buffer (app_main's stack) */
    lbj_rx_t rx;
    uint8_t  count, cur, prevKey, redraw, page, top;
    bool     running, spk, blAlways, en, sessValid;
    uint8_t  busyFor, ledPhase;   /* ledPhase: green-LED double-blink steps */
    char     sess[16];         /* last 1233999/1234000 short block (train/spd/km) */
    int32_t  rssi;
    uint32_t tPrev, tCyc, rssiMs;
    uint32_t savedSqr3, savedSmpr3;
} g;
#define str g.text

/* ---- tiny freestanding helpers ---- */
void *memset(void *d, int c, size_t n){ uint8_t *p=d; while(n) p[--n]=(uint8_t)c; return d; }
void *memcpy(void *d, const void *s, size_t n){ uint8_t *p=d; const uint8_t *q=s; while(n){--n;p[n]=q[n];} return d; }

/* ---- formatting (repeated subtraction: no division) ---- */
static char *put(char *o,const char *s){ while(*s)*o++=*s++; return o; }
static unsigned sub(uint32_t *v,uint32_t d){ unsigned q=0; while(*v>=d){ *v-=d; q++; } return q; }
static const uint32_t P10U[]={1000000u,100000u,10000u,1000u,100u,10u,1u};
static char *putu(char *o,uint32_t v){
    bool lead=false;
    for(uint8_t i=0;i<7u;i++){
        unsigned c=sub(&v,P10U[i]);
        if(c||lead||i==6u){ *o++=(char)('0'+c); lead=true; }
    }
    return o;
}
/* decimal value of up to n chars (non-digits ignored) */static uint32_t digv(const char *p,uint8_t n){
    uint32_t v=0;
    for(uint8_t i=0;i<n;i++){ char c=p[i]; if(c>='0'&&c<='9') v=v*10u+(uint32_t)(c-'0'); }
    return v;
}
/* 5 BCD chars -> DDDD.D (blank / non-digit -> 0) */
static char *putkm(char *o,const char *p){
    for(uint8_t i=0;i<4u;i++){ char c=p[i]; *o++=(c>='0'&&c<='9')?c:'0'; }
    *o++='.';
    char c=p[4]; *o++=(c>='0'&&c<='9')?c:'0';
    return o;
}

/* DMS BCD (DDDMM.MMMM / DDMM.MMMM) -> decimal degrees with 4 decimals:
 * v = degrees*10000 + (minutes x10000)/60, then split. No float and no
 * division: sub() is repeated subtraction, so libgcc's __udivsi3 stays out.
 * Needs dg+6 chars at p. Two calls per redraw, worst case ~2 ms. */
static char *putdec(char *o,const char *p,uint8_t dg){
    uint32_t m=digv(p+dg,6u);                       /* MM.MMMM as x10000 */
    uint32_t v=digv(p,dg)*10000u+(uint32_t)sub(&m,60u);
    o=putu(o,sub(&v,10000u));                       /* whole degrees */
    *o++='.';
    for(uint8_t i=3u;i<7u;i++) *o++=(char)('0'+sub(&v,P10U[i]));
    return o;
}

#define ROWY(i) ((uint8_t)((i)*8u))

/* ---- PA4 bias (AC-coupled audio needs a mid-scale reference; EPIRB 406) ---- */
static void biasOn(uint32_t moder,uint32_t rcc){
    GPIOA_MODER=moder|(3u<<8);
    RCC_APBENR1=rcc|RCC_DACEN;
    DAC_CR=DAC_CR_BIAS;
    DAC_DHR12R1=BIAS_CODE;
    DAC_SWTRIGR=1u;
}
static void biasOff(uint32_t dac,uint32_t dhr,uint32_t rcc,uint32_t moder){
    DAC_CR=dac; DAC_DHR12R1=dhr; RCC_APBENR1=rcc; GPIOA_MODER=moder;
}
static void adcSelPA4(void){
    ADC_SMPR3=(g.savedSmpr3&~(7u<<SMP4_POS))|(((g.savedSmpr3>>SMP8_POS)&7u)<<SMP4_POS);
    ADC_SQR3=(g.savedSqr3&~0x1Fu)|ADC_CH_PA4;
}
static void adcRestore(void){ ADC_SQR3=g.savedSqr3; ADC_SMPR3=g.savedSmpr3; }
static uint16_t adcRead(void){
    ADC_CR2|=ADC_CR2_START;
    for(uint16_t n=0; !(ADC_SR&ADC_SR_EOC) && n<2000u; n++){}
    return (uint16_t)(ADC_DR&0x0FFFu);
}

/* ---- SysTick cycle counter (call at least every 10 ms) ---- */
static void clkStart(void){ g.tPrev=SYST_VAL; g.tCyc=0; }
static uint32_t clkCyc(void){
    uint32_t v=SYST_VAL;
    g.tCyc += (v<=g.tPrev) ? g.tPrev-v : g.tPrev+(SYST_LOAD+1u-v);
    g.tPrev=v;
    return g.tCyc;
}

/* ---- one ADC sample through the model (DemodInt.sample) ---- */
static void dem_sample(dem_t *m,int32_t x){
    m->dc += (x - m->dc) >> DC_SHIFT;
    int32_t y = x - m->dc;
    int32_t o = (M_B0*y + M_B1*m->x1 + M_B0*m->x2 - M_A1*m->y1 - M_A2*m->y2) >> 14;
    m->x2=m->x1; m->x1=y; m->y2=m->y1; m->y1=o;
    /* One-bit matched filter: running sum of the last BOX samples. The sum is
     * BOX times the mean, but the slicer tracks its own peak-to-peak, so no
     * division is needed. Its null at the bit rate also rejects the data
     * harmonics (the weak-signal win). */
    m->bsum += o - m->box[m->bi];
    m->box[m->bi] = (int16_t)o;
    m->bi = (uint8_t)((m->bi + 1u) & (BOX - 1u));
    y = m->bsum;
    m->hi -= (m->hi - y) >> PK_SHIFT;
    if(y > m->hi) m->hi = y;
    m->lo += (y - m->lo) >> PK_SHIFT;
    if(y < m->lo) m->lo = y;
    /* Hysteresis slice (as the reference _d8): only flip beyond the mid +/- h
     * band, so noise near the threshold neither flips the bit nor kicks the
     * DPLL. */
    const int32_t mid = (m->hi + m->lo) >> 1;
    const int32_t h = (m->hi - m->lo) >> 6;
    uint8_t level = m->last;
    if(y > mid + h) level = 1u; else if(y < mid - h) level = 0u;
    if(level != m->last){
        int32_t err = m->ph;
        if(err > 32768) err -= 65536;
        m->iint += err >> INT_SHIFT;
        if(m->iint > INT_MAX) m->iint = INT_MAX; else if(m->iint < -INT_MAX) m->iint = -INT_MAX;
        m->ph -= (err >> PLL_SHIFT) + m->iint;
        if(m->ph < 0) m->ph += 65536; else if(m->ph >= 65536) m->ph -= 65536;
    }
    m->last = level;
    int32_t p0 = m->ph;
    m->ph += PLL_STEP;
    if(p0 < 32768 && m->ph >= 32768) lbj_rx_bit(&g.rx, level);
    if(m->ph >= 65536) m->ph -= 65536;
}

/* ---- callbacks from the decoder core ---- */
/* LBJ address family receive window (matches the upstream receiver):
 * 1233980..1234020. Anything else is other POCSAG traffic and is dropped
 * before it can reach the history (note: the #if 0 PDU page used to show
 * every address - restore this filter's removal together with that page). */
static bool in_lbj(uint32_t a){ return (uint32_t)(a - 1233980u) <= 40u; }
/* The addresses the SUM page knows how to lay out: 1233999..1234002. */
static bool is_lbj(uint32_t a){ return (uint32_t)(a - 1233999u) <= 3u; }

/* ---- new-generation LB alert: the detail block -------------------------
 * 1234001/1234002: standalone detail of 30..64 chars at [0:len), or merged
 * after a 15-char short prefix ([15:65] of a 65-char report).
 * 1233999/1234000: only the merged form (len >= 65).
 * Inside the block: [0:4] 2 ASCII prefix chars, [4:7] 3-digit model code,
 * [7:12] loco number, [12:14] end flag, [14:30] GB2312 route, [30:39] and
 * [39:47] DDDMM.MMMM / DDMM.MMMM coordinates. */
#define DET_NIB    50u         /* detail block length (nibbles)   */
#define DET_MERGED 65u         /* 15-char short block + 50 detail */
#define DET_MIN30  30u         /* shortest standalone detail      */

/* true when the record carries a decodable detail block. */
static bool hasdet(uint32_t a,uint8_t len){
    if(!is_lbj(a)) return false;                 /* only 1233999..1234002 */
    if(a>=1234001u) return len>=DET_MIN30;       /* 1234001/1234002: standalone or merged */
    return len>=DET_MERGED;                      /* 1233999/1234000: merged only */
}

void lbj_emit_msg(const lbj_rx_t *r, const char *bcd, uint16_t len){
    if(!in_lbj(r->addr)) return;      /* keep the LBJ family only */
    g.A->backlight_on();              /* wake the screen on RX activity */
    g.ledPhase=4u;                    /* green LED: on/off/on/off, 10 ms a step */
    rec_t *rec=g.hist[HISTORY-1u];
    for(uint8_t k=HISTORY-1u;k;k--) g.hist[k]=g.hist[k-1u];
    g.hist[0]=rec;
    rec->addr=r->addr;
    rec->func=r->func;
    /* rec->flags (RF_ERR/RF_LBJ) is only read by the #if 0 PDU page. */
    /* rec->flags=(uint8_t)((r->err?RF_ERR:0u) | (is_lbj(r->addr)?RF_LBJ:0u)); */
    rec->len=(uint8_t)(len>BCDMAX?BCDMAX:len);
    for(uint8_t i=0;i<rec->len;i++) rec->bcd[i]=bcd[i];
    if((r->addr==1233999u||r->addr==1234000u) && len>=15u){   /* remember the short block */
        for(uint8_t i=0;i<15u;i++) g.sess[i]=bcd[i];
        g.sessValid=true;
    }
    if(g.count<HISTORY) g.count++;
    g.cur=0;
    g.redraw=1u;
}

/* ---- display ---- */
#if 0   /* DEBUG: shared counter row (M/S/W/F/B). Disabled to fit the 4 KiB
         * overlay; restore together with the PDU page below AND the counter
         * fields in lbj_rx_t (lbj_dec.h) plus their increments in lbj_dec.c. */
static void counters(uint8_t y){
    char *o=str;
    *o++='M'; o=putu(o,g.rx.msgs);
    *o++=' '; *o++='S'; o=putu(o,g.rx.syncs);
    *o++=' '; *o++='W'; o=putu(o,g.rx.words);
    *o++=' '; *o++='F'; o=putu(o,g.rx.fix);
    *o++=' '; *o++='B'; o=putu(o,g.rx.bad);
    tiny(y,o);
}
#endif
/* bcd char -> raw 4-bit value (inverse of the decoder's BCD alphabet). */
static uint8_t nib(char c){
    if(c>='0'&&c<='9') return (uint8_t)(c-'0');
    switch(c){
        case '*': return 10u; case 'U': return 11u; case ' ': return 12u;
        case '-': return 13u; case ')': return 14u; case '(': return 15u;
        default:  return 0u;
    }
}
/* Binary search the sorted u16 model-code asset; returns the index or -1. */
static int type_index(uint16_t code){
    int lo=0, hi=(int)TY_COUNT-1;
    while(lo<=hi){
        int mid=(lo+hi)>>1;
        uint16_t c=0;
        g.A->asset_read((uint16_t)(TY_CODE+(uint16_t)mid*2u),&c,2u);
        if(c==code) return mid;
        if(c<code) lo=mid+1; else hi=mid-1;
    }
    return -1;
}

/* Bottom status bar (tiny 3x5): key-state hints (5 language / 4 backlight /
 * 1 speaker), then x/y (selected / total, 1 = newest) and the live RSSI
 * (-xx dBm). Refreshed every 0.5 s in house(); drawn even before the first
 * message (0/0) so it is visible from launch. Worst case 32 chars = 128 px. */
static void drawFooter(const char *s){
    static const uint8_t LAB[3]={T_L5,T_BL,T_SPK};   /* key-state hint labels */
    uint8_t val[3];
    val[0]=g.en?T_EN:T_ZH; val[1]=g.blAlways?T_ON:T_OFF; val[2]=g.spk?T_ON:T_OFF;
    char *o=str;
    for(uint8_t i=0;i<3u;i++){ if(i) *o++=' '; o=put(o,s+LAB[i]); o=put(o,s+val[i]); }
    *o++=' ';
    o=putu(o, g.count ? (uint32_t)g.cur+1u : 0u);
    *o++='/';
    o=putu(o,g.count);
    *o++=' ';
    int32_t r=g.rssi;
    if(r<0){ *o++='-'; r=-r; }
    o=putu(o,(uint32_t)r);
    *o='\0';
    g.A->print_tiny(str,0,ROWY(6),false,true);
}

/* Append "<train> <dir>" from the short block sb (6 chars); used by both the
 * short and the 1234002 layouts. */
static char *puttrain(char *o,const char *sb,const char *s,uint8_t func,bool have){
    if(!have){ *o++='-'; *o++='-'; }
    else for(uint8_t i=0;i<6u;i++) if(sb[i]!=' ') *o++=sb[i];
    *o++=' ';
    return put(o,(func==1u)?s+T_DN:((func==3u)?s+T_UP:s+T_UNK));
}

/* SUM page. 1233999/1234000 (short): train/dir, SPEED, KM, address value.
 * 1234001/1234002 (detail): train/dir + model + route, speed/km, LON/LAT
 * (tiny font), address value. A merged 65-char report carries its own short
 * prefix; a standalone detail (30..64 chars) borrows the most recent short
 * report kept in g.sess. */
__attribute__((noinline))
static void drawSummary(char *s){
    const app_api_t *A=g.A;
    char *o;
    if(!g.count){ drawFooter(s); return; }
    const rec_t *rec=g.hist[g.cur];
    const char *b=rec->bcd;
    const bool det=hasdet(rec->addr,rec->len);

    if(det){
        const bool merged=(rec->len>=DET_MERGED);
        const uint8_t start=merged?(uint8_t)(rec->len-DET_NIB):0u;
        const char *d=b+start;                 /* the 50-char (or shorter) block */
        const uint8_t dlen=(uint8_t)(rec->len-start);
        const char *sb=merged?b:g.sess;        /* merged carries its own short block */
        const bool have=merged||g.sessValid;

        /* row0: train + direction. */
        o=str; o=puttrain(o,sb,s,rec->func,have); *o='\0';
        A->print_bold(str,0,0,0);

        /* row1: model name (CN) / abbreviation (EN) + registration number.
         * The 3-digit model code is [4:7] (the 2 ASCII prefix chars are at
         * [0:4]); [4:12] as a whole is the 8-char code+number registration. */
        o=str;
        {
            char nb[TY_NAME_STRIDE];
            int idx=type_index((uint16_t)digv(d+4u,3u));
            if(idx<0) o=put(o,"--");
            else {
                if(g.en) A->asset_read((uint16_t)(TY_EN+(uint16_t)idx*TY_EN_STRIDE),nb,TY_EN_STRIDE);
                else     A->asset_read((uint16_t)(TY_NAME+(uint16_t)idx*TY_NAME_STRIDE),nb,TY_NAME_STRIDE);
                o=put(o,nb);
            }
        }
        *o++=' ';
        for(uint8_t i=4u;i<12u;i++) *o++=d[i];   /* the 8-char code+number registration */
        *o='\0';
        A->print_bold(str,0,0,1);

        /* row2: route (GB2312), no label; hidden in English mode. */
        if(!g.en){
            o=str;
            for(uint8_t i=0;i<8u;i++){ uint8_t v=(uint8_t)((nib(d[14u+i*2u])<<4)|nib(d[15u+i*2u])); if(!v) break; *o++=(char)v; }
            *o='\0';
            A->print_bold(str,0,0,2);
        }

        /* row3: speed and position km (from the short prefix / last report). */
        o=str; o=put(o,s+T_SPD2);
        if(have){ o=putu(o,digv(sb+6u,3u)); o=put(o,s+T_KM); o=putkm(o,sb+10u); }
        else o=put(o,"--");
        *o='\0';
        A->print_bold(str,0,0,3);

        /* row4: longitude/latitude in decimal degrees (tiny font). Only the
         * full 50-char block carries the coordinates; a short standalone
         * detail stops before them. */
        if(dlen>=47u){
            o=str;
            o=put(o,s+T_LON); o=putdec(o,d+30u,3u); *o++=' ';
            o=put(o,s+T_LAT); o=putdec(o,d+39u,2u);
            *o='\0';
            A->print_tiny(str,0,ROWY(4),false,true);
        }

        /* row5: the decoded address value. */
        o=str; o=putu(o,rec->addr); *o='\0';
        A->print_bold(str,0,0,5);
    } else {
        /* row0: train + direction. */
        o=str; o=puttrain(o,b,s,rec->func,rec->len>=6u); *o='\0';
        A->print_bold(str,0,0,0);
        /* row1: SPEED xx km/h. */
        o=str; o=put(o,s+T_SPD); o=putu(o,digv(b+6u,3u)); o=put(o,s+T_KMH); *o='\0';
        A->print_bold(str,0,0,1);
        /* row2: KM xxxx.x. */
        o=str; o=put(o,s+T_KM);
        if(rec->len>=15u) o=putkm(o,b+10u); else o=put(o,"--");
        *o='\0';
        A->print_bold(str,0,0,2);
        /* row3: the decoded address value. */
        o=str; o=putu(o,rec->addr); *o='\0';
        A->print_bold(str,0,0,3);
    }

    drawFooter(s);
}

#if 0   /* DEBUG: the PDU page (all messages + address/func/LBJ/BCH + raw BCD).
         * Disabled to fit the 4 KiB overlay; the app is SUM-only for now.
         * Restore with the counters row above and the key-3 page switch. */
/* All decoded messages, any address (page 1); the debug info lives here. */
__attribute__((noinline))
static void drawPdus(char *s){
    if(!g.count){ if(g.A->ticks_ms()&512u) tiny(ROWY(1),put(str,s+T_WAIT)); counters(ROWY(6)); return; }
    uint8_t shown=0;
    for(uint8_t i=g.top;i<g.count && shown<3u;i++,shown++){
        const rec_t *rec=g.hist[i];
        const char *b=rec->bcd;
        char *o=str;
        *o++='A'; o=putu(o,rec->addr);
        *o++=' '; *o++='F'; *o++=(char)('0'+rec->func);
        *o++=' '; o=put(o,(rec->flags&RF_LBJ)?s+T_LBJ:s+T_NOLBJ);
        *o++=' '; *o++=(rec->flags&RF_ERR)?'!':'+';
        tiny(ROWY((uint8_t)(shown*2u)),o);
        o=str; uint8_t n=(uint8_t)(rec->len<32u?rec->len:32u);
        for(uint8_t k=0;k<n;k++) *o++=safe((uint8_t)b[k]);
        tiny(ROWY((uint8_t)(shown*2u+1u)),o);
    }
    counters(ROWY(6));
}
#endif

__attribute__((noinline))
static void draw(void){
    const app_api_t *A=g.A;
    char s[UI_SIZE] __attribute__((aligned(4)));
    A->asset_read(0,s,UI_SIZE);
    A->display_clear();
    A->status_clear();
    A->print_inverse(s+T_TITLE,2,0,true,true,(uint8_t)(2u+T_TITLE_CHARS*4u));
    A->draw_battery();
    /* Page indicator and the PDU page are disabled (SUM-only); see the #if 0
     * blocks for the removed code. */
    drawSummary(s);

    /* Frequency on the status bar: the framebuffer is only FRAME_LINES (7) rows
     * tall, so a y >= 56 would write past gFrameBuffer. */
    char *f=str; uint32_t fr=A->rx_freq();
    f=putu(f,sub(&fr,100000u)); *f++='.';
    *f++=(char)('0'+sub(&fr,10000u)); *f++=(char)('0'+sub(&fr,1000u));
    *f++=(char)('0'+sub(&fr,100u)); *f++=(char)('0'+sub(&fr,10u));
    *f='\0';
    A->print_tiny(str,46,0,true,true);

    A->blit_status();
    A->blit_full();
}

/* ---- input ---- */
static void handleKeys(void){
    const app_api_t *A=g.A;
    uint8_t key=A->get_key();
    /* One step per press: acting on the raw held key every house slot would
     * auto-repeat at ~20/s and skip records. Only a new key does anything, and
     * after release (prevKey=INVALID) nothing moves until the next press. */
    if(key==APP_KEY_INVALID||key==g.prevKey){ g.prevKey=key; return; }
    g.prevKey=key;
    int d=A->nav_dir(key);
    if(d){
        /* SUM only: one step per press through the record history. */
        int t=(int)g.cur+d;
        if(t<0) t=0;
        if(t>=(int)g.count) t=(int)g.count-1;
        if(t<0) t=0;
        if((uint8_t)t!=g.cur){ g.cur=(uint8_t)t; g.redraw=1u; }
        return;
    }
    g.redraw=1u;
    switch(key){
        case APP_KEY_EXIT: g.running=false; break;
        case APP_KEY_1:    g.spk=!g.spk; A->audio_path(g.spk); break;
        case APP_KEY_2:    g.count=g.cur=g.top=0;
                           /* reset the debug counters too (see lbj_dec.h):
                            * g.rx.syncs=g.rx.words=g.rx.ok=g.rx.fix=g.rx.bad=0;
                            * g.rx.msgs=g.rx.up=g.rx.dn=0; */
                           g.sessValid=false; break;
        /* case APP_KEY_3: g.page^=1u; g.top=0; g.cur=0; break;  PDU page off */
        case APP_KEY_4:    g.blAlways=!g.blAlways;
                           A->backlight_on();   /* re-arm now; house() holds it on when ON */
                           break;
        case APP_KEY_5:    g.en=!g.en; break;   /* Chinese / English display */
        default: break;
    }
}

/* ---- keys and screen, between frames ---- */
static void house(void){
    const app_api_t *A=g.A;
    handleKeys();
    if(!g.running) return;
    g.rssi=A->rssi_dbm();
    uint32_t now=A->ticks_ms();
    if((uint32_t)(now-g.rssiMs)>=500u){ g.rssiMs=now; g.redraw=1u; }  /* RSSI every 0.5 s */
    if(g.blAlways) A->backlight_on();   /* re-arm BLTime every slot so it never expires */
    /* The fade only advances inside BACKLIGHT_Update(), which this service
     * drives: without it a dark panel would never light up after key 4 or a
     * decode wake-up (TurnOn just sets the target brightness). */
    A->backlight_update();
    if(!g.redraw) return;
    g.redraw=0;
    adcRestore();
    A->battery_sample();
    adcSelPA4();
    draw();
}

__attribute__((noinline))
static void listen(void){
    dem_t dm;                       /* on the stack: .bss counts toward the 4 KiB */
    memset(&dm,0,sizeof dm);
    dm.dc=BIAS_CODE; dm.hi=200; dm.lo=-200;   /* bsum is DC-free */

    adcSelPA4();
    clkStart();
    uint32_t next=0;
    uint16_t cnt=0;
    uint8_t  ledCnt=0;
    g.redraw=1u;
    while(g.running){
        while((int32_t)(clkCyc()-next)<0){}
        next+=CYC_PER_SAMPLE;
        dem_sample(&dm,adcRead());
        /* Green-LED double-blink: one step every 192 samples (10 ms). The
         * BK4819 GPIO6 write costs ~40 us (< one sample period), so the
         * sampler is not disturbed. */
        if(++ledCnt>=192u){ ledCnt=0; if(g.ledPhase){ g.A->led((g.ledPhase&1u)==0u); g.ledPhase--; } }
        if(++cnt<HOUSE_EVERY) continue;
        cnt=0;
        if(g.rx.inmsg && ++g.busyFor<BUSY_MAX) continue;   /* keep sampling a message */
        g.busyFor=0;
        house();
        next=clkCyc();
    }
    adcRestore();
}

__attribute__((section(".text.entry"),used))
void app_main(const app_api_t *api){
    rec_t recs[HISTORY];
    rec_t *hist[HISTORY];
    char text[40];
    for(uint8_t k=0;k<HISTORY;k++) hist[k]=&recs[k];
    g.A=api;
    g.hist=hist;
    g.text=text;
    g.prevKey=APP_KEY_INVALID;
    g.savedSqr3=ADC_SQR3; g.savedSmpr3=ADC_SMPR3;
    const uint32_t savedModer=GPIOA_MODER, savedDac=DAC_CR;
    const uint32_t savedRcc=RCC_APBENR1, savedDhr=DAC_DHR12R1;
    biasOn(savedModer,savedRcc);
    api->backlight_on();

    uint8_t cfg=0;
    api->cfg_load(&cfg,1);
    g.spk=(cfg&1u)!=0u;
    g.en =(cfg&2u)!=0u;       /* bit1 set = ASCII fallback (no Chinese font) */
    g.page=0;

    /* RAW RX: HPF/LPF, de-emphasis and AFC off (EPIRB 406); the loader restores
     * the registers through RADIO_SetupRegisters on exit. */
    api->bk_write(REG_2B,(uint16_t)((api->bk_read(REG_2B)|0x0700u)&~0x0007u));
    api->bk_write(REG_73,(uint16_t)(api->bk_read(REG_73)|0x0010u));
    api->audio_path(g.spk);
    api->set_af(APP_AF_FM);
    api->delay_ms(50);

    g.running=true;
    listen();

    biasOff(savedDac,savedDhr,savedRcc,savedModer);
    api->led(false);           /* do not leave the green LED stuck mid-blink */
    api->set_af(APP_AF_MUTE);
    api->audio_path(false);
    cfg=(uint8_t)((g.spk?1u:0u)|(g.en?2u:0u));
    api->cfg_save(&cfg,1);
}
