/* Copyright 2026
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * LBJ RX (development build) - receives Chinese railway LBJ (POCSAG 1200 baud,
 * direct FSK, ~821.24 MHz) and shows every decoded POCSAG message plus the
 * receive chain stats for debugging. Reference: Sdr-Is-Fun/RTL_SDR_LBJ_RECEIVER
 * and APRS RX on this firmware.
 *
 * The BK4829 has no POCSAG/FM-data demodulator, so as EPIRB 406 / APRS RX do,
 * the RX audio reaches PA4 (voice DAC pin, held at mid-scale by the MCU DAC) and
 * is sampled on ADC channel 4 at 9.6 kHz (8 samples per 1200-baud bit), timed
 * from SysTick, continuously. The receiver is switched to RAW (RX HPF/LPF,
 * de-emphasis and AFC off): the de-emphasis would destroy the NRZ baseband.
 * Each sample goes through the model in test/model_rx.py: slow baseline tracker,
 * low-pass biquad, symmetric peak tracker, DPLL (65536/bit), then POCSAG sync /
 * batch / BCH(31,21) single-bit correction and the LBJ BCD layout.
 *
 * Keys: 3 toggles the debug pages (SUMmary / all PDUs); UP/DOWN pick the
 * newer/older record or scroll; 1 speaker; 2 clear; EXIT quit. Every page foots
 * a shared counter row: M<msgs> S<sync> W<words> F<fixed> B<bad>.
 */

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>
#include "../app_api.h"
#include "lbj_assets.h"        /* generated by gen_assets.py */
#include "lbj_dec.h"
#include "lbj_dec.c"           /* the POCSAG/LBJ core (same translation unit) */

/* ---- MCU registers (PY32F071, core and SysTick at 48 MHz, 10 ms period) ---- */
static inline volatile uint32_t *hw(uint32_t a){
    volatile uint32_t *p=(volatile uint32_t *)a;
    __asm__("" : "+l"(p));
    return p;
}
#define SYST_LOAD   (*(volatile uint32_t *)0xE000E014u)
#define SYST_VAL    (*(volatile uint32_t *)0xE000E018u)
#define ADC_SR      (hw(0x40012400u)[0x00/4])
#define ADC_CR2     (hw(0x40012400u)[0x08/4])
#define ADC_SMPR3   (hw(0x40012400u)[0x14/4])
#define ADC_SQR3    (hw(0x40012400u)[0x38/4])
#define ADC_DR      (hw(0x40012400u)[0x50/4])
#define GPIOA_MODER (*(volatile uint32_t *)0x50000000u)
#define DAC_CR      (hw(0x40007400u)[0x00/4])
#define DAC_SWTRIGR (hw(0x40007400u)[0x04/4])
#define DAC_DHR12R1 (hw(0x40007400u)[0x08/4])
#define RCC_APBENR1 (*(volatile uint32_t *)0x4002103Cu)
#define RCC_DACEN   (1u << 29)
#define DAC_CR_BIAS ((1u << 0) | (1u << 1) | (1u << 2) | (7u << 3))
#define BIAS_CODE   2048u
#define ADC_SR_EOC     (1u << 1)
#define ADC_CR2_START  ((1u << 22) | (1u << 20))
#define SMP8_POS       24u
#define SMP4_POS       12u
#define ADC_CH_PA4     4u
#define FS             9600u
#define CYC_PER_SAMPLE (48000000u / FS)
#define HOUSE_EVERY    480u    /* samples between key/screen slots (50 ms) */
#define BUSY_MAX       100u    /* serve keys anyway after 5 s inside a message */

#define REG_2B  0x2Bu          /* RX HPF/LPF + de-emphasis + AFC (EPIRB 406 RAW) */
#define REG_73  0x73u

/* ---- demodulator (test/model_rx.py, class DemodInt; the C is a transcription) */
#define DC_SHIFT   7
#define PK_SHIFT   8
#define PLL_STEP   8192        /* 65536 per bit / 8 samples per bit */
#define PLL_SHIFT  3
#define INT_SHIFT  9
#define INT_MAX    164
#define M_B0       2293        /* low-pass biquad 1500 Hz @ 9.6 kHz, Q14 */
#define M_B1       4586
#define M_A1     (-11465)
#define M_A2       4252

typedef struct {
    int32_t dc;
    int32_t x1, x2, y1, y2;
    int32_t hi, lo;
    int32_t ph, iint;
    uint8_t last;
} dem_t;

/* ---- decoded-message history ---- */
#define HISTORY   8u
#define BCDMAX    96u

typedef struct {
    uint32_t addr;
    uint8_t  func, flags, len;
    char     bcd[BCDMAX];
} rec_t;
#define RF_ERR  1u             /* BCH could not correct the report */
#define RF_LBJ  2u             /* address belongs to the LBJ set */

static struct {
    const app_api_t *A;
    rec_t **hist;              /* newest first; records live on app_main's stack */
    char   *text;              /* formatting buffer (app_main's stack) */
    lbj_rx_t rx;
    dem_t    dem;
    uint8_t  count, cur, prevKey, redraw, page, top;
    bool     running, spk;
    uint8_t  busyFor;
    int32_t  rssi;
    uint32_t tPrev, tCyc;
    uint32_t savedSqr3, savedSmpr3;
} g;
#define str g.text

/* ---- tiny freestanding helpers ---- */
void *memset(void *d, int c, size_t n){ uint8_t *p=d; while(n) p[--n]=(uint8_t)c; return d; }
void *memcpy(void *d, const void *s, size_t n){ uint8_t *p=d; const uint8_t *q=s; while(n){--n;p[n]=q[n];} return d; }

/* ---- formatting (repeated subtraction: no division) ---- */
static char *put(char *o,const char *s){ while(*s)*o++=*s++; return o; }
static unsigned sub(uint32_t *v,uint32_t d){ unsigned q=0; while(*v>=d){ *v-=d; q++; } return q; }
static const uint32_t P10U[]={1000000u,100000u,10000u,1000u,100u,10u,1u};
static char *putu(char *o,uint32_t v){
    bool lead=false;
    for(uint8_t i=0;i<7u;i++){
        unsigned c=sub(&v,P10U[i]);
        if(c||lead||i==6u){ *o++=(char)('0'+c); lead=true; }
    }
    return o;
}
static char *puti(char *o,int32_t v){
    if(v<0){ *o++='-'; return putu(o,(uint32_t)(-v)); }
    return putu(o,(uint32_t)v);
}
static char safe(uint8_t c){ return (c<0x20u||c>0x7Eu)?'.':(char)c; }
static void tiny(uint8_t y,char *end){ *end='\0'; g.A->print_tiny(str,0,y,false,true); }

#define ROWY(i) ((uint8_t)((i)*8u))

/* ---- PA4 bias (AC-coupled audio needs a mid-scale reference; EPIRB 406) ---- */
static void biasOn(uint32_t moder,uint32_t rcc){
    GPIOA_MODER=moder|(3u<<8);
    RCC_APBENR1=rcc|RCC_DACEN;
    DAC_CR=DAC_CR_BIAS;
    DAC_DHR12R1=BIAS_CODE;
    DAC_SWTRIGR=1u;
}
static void biasOff(uint32_t dac,uint32_t dhr,uint32_t rcc,uint32_t moder){
    DAC_CR=dac; DAC_DHR12R1=dhr; RCC_APBENR1=rcc; GPIOA_MODER=moder;
}
static void adcSelPA4(void){
    ADC_SMPR3=(g.savedSmpr3&~(7u<<SMP4_POS))|(((g.savedSmpr3>>SMP8_POS)&7u)<<SMP4_POS);
    ADC_SQR3=(g.savedSqr3&~0x1Fu)|ADC_CH_PA4;
}
static void adcRestore(void){ ADC_SQR3=g.savedSqr3; ADC_SMPR3=g.savedSmpr3; }
static uint16_t adcRead(void){
    ADC_CR2|=ADC_CR2_START;
    for(uint16_t n=0; !(ADC_SR&ADC_SR_EOC) && n<2000u; n++){}
    return (uint16_t)(ADC_DR&0x0FFFu);
}

/* ---- SysTick cycle counter (call at least every 10 ms) ---- */
static void clkStart(void){ g.tPrev=SYST_VAL; g.tCyc=0; }
static uint32_t clkCyc(void){
    uint32_t v=SYST_VAL;
    g.tCyc += (v<=g.tPrev) ? g.tPrev-v : g.tPrev+(SYST_LOAD+1u-v);
    g.tPrev=v;
    return g.tCyc;
}

/* ---- one ADC sample through the model (DemodInt.sample) ---- */
static void dem_sample(int32_t x){
    dem_t *m=&g.dem;
    m->dc += (x - m->dc) >> DC_SHIFT;
    int32_t y = x - m->dc;
    int32_t o = (M_B0*y + M_B1*m->x1 + M_B0*m->x2 - M_A1*m->y1 - M_A2*m->y2) >> 14;
    m->x2=m->x1; m->x1=y; m->y2=m->y1; m->y1=o;
    y=o;
    m->hi -= (m->hi - y) >> PK_SHIFT;
    if(y > m->hi) m->hi = y;
    m->lo += (y - m->lo) >> PK_SHIFT;
    if(y < m->lo) m->lo = y;
    uint8_t level = (y > ((m->hi + m->lo) >> 1)) ? 1u : 0u;
    if(level != m->last){
        int32_t err = m->ph;
        if(err > 32768) err -= 65536;
        m->iint += err >> INT_SHIFT;
        if(m->iint > INT_MAX) m->iint = INT_MAX; else if(m->iint < -INT_MAX) m->iint = -INT_MAX;
        m->ph -= (err >> PLL_SHIFT) + m->iint;
        if(m->ph < 0) m->ph += 65536; else if(m->ph >= 65536) m->ph -= 65536;
    }
    m->last = level;
    int32_t p0 = m->ph;
    m->ph += PLL_STEP;
    if(p0 < 32768 && m->ph >= 32768) lbj_rx_bit(&g.rx, level);
    if(m->ph >= 65536) m->ph -= 65536;
}

/* ---- callbacks from the decoder core ---- */
static bool is_lbj(uint32_t a){ return (uint32_t)(a - 1233999u) <= 3u; }
void lbj_emit_msg(const lbj_rx_t *r, const char *bcd, uint16_t len){
    rec_t *rec=g.hist[HISTORY-1u];
    for(uint8_t k=HISTORY-1u;k;k--) g.hist[k]=g.hist[k-1u];
    g.hist[0]=rec;
    rec->addr=r->addr;
    rec->func=r->func;
    rec->flags=(uint8_t)((r->err?RF_ERR:0u) | (is_lbj(r->addr)?RF_LBJ:0u));
    rec->len=(uint8_t)(len>BCDMAX?BCDMAX:len);
    for(uint8_t i=0;i<rec->len;i++) rec->bcd[i]=bcd[i];
    if(g.count<HISTORY) g.count++;
    g.cur=0;
    g.redraw=1u;
}

/* ---- display ---- */
/* Shared footer: message / sync / word / fixed / bad counts. */
static void counters(uint8_t y){
    char *o=str;
    *o++='M'; o=putu(o,g.rx.msgs);
    *o++=' '; *o++='S'; o=putu(o,g.rx.syncs);
    *o++=' '; *o++='W'; o=putu(o,g.rx.words);
    *o++=' '; *o++='F'; o=putu(o,g.rx.fix);
    *o++=' '; *o++='B'; o=putu(o,g.rx.bad);
    tiny(y,o);
}
/* Live front-end values: peak-to-peak, baseline, RSSI. */
static void sigrow(uint8_t y){
    char *o=str;
    *o++='p'; *o++='p'; *o++=' '; o=putu(o,(uint32_t)(g.dem.hi-g.dem.lo));
    *o++=' '; *o++='d'; o=puti(o,g.dem.dc);
    *o++=' '; *o++='R'; o=puti(o,g.rssi);
    tiny(y,o);
}

__attribute__((noinline))
static void drawSummary(char *s){
    const app_api_t *A=g.A;
    char *o;
    if(!g.count){ if(A->ticks_ms()&512u) tiny(ROWY(1),put(str,s+T_WAIT)); counters(ROWY(6)); return; }
    const rec_t *rec=g.hist[g.cur];
    const char *b=rec->bcd;
    uint8_t n=(uint8_t)(rec->len<6u?rec->len:6u);
    o=str; for(uint8_t i=0;i<n;i++) if(b[i]!=' ') *o++=safe((uint8_t)b[i]);
    *o++=' ';
    o=put(o, rec->func==1u?s+T_DN:(rec->func==3u?s+T_UP:s+T_UNK));
    A->print_bold(str,0,0,0);
    o=str; o=put(o,s+T_SPD);
    for(uint8_t i=6;i<9u&&i<rec->len;i++) *o++=safe((uint8_t)b[i]);
    o=put(o,s+T_KM);
    for(uint8_t i=10;i<15u&&i<rec->len;i++) *o++=safe((uint8_t)b[i]);
    tiny(ROWY(1),o);
    o=str; *o++='A'; o=putu(o,rec->addr);
    *o++=' '; *o++='F'; *o++=(char)('0'+rec->func);
    *o++=' '; o=put(o,(rec->flags&RF_LBJ)?s+T_LBJ:s+T_NOLBJ);
    *o++=' '; *o++=(rec->flags&RF_ERR)?'!':'+';
    tiny(ROWY(2),o);
    o=str; n=(uint8_t)(rec->len<32u?rec->len:32u);
    for(uint8_t i=0;i<n;i++) *o++=safe((uint8_t)b[i]);
    tiny(ROWY(3),o);
    sigrow(ROWY(4));
    counters(ROWY(6));
}

/* All decoded messages, any address (page 1). */
__attribute__((noinline))
static void drawPdus(char *s){
    if(!g.count){ if(g.A->ticks_ms()&512u) tiny(ROWY(1),put(str,s+T_WAIT)); counters(ROWY(6)); return; }
    uint8_t shown=0;
    for(uint8_t i=g.top;i<g.count && shown<3u;i++,shown++){
        const rec_t *rec=g.hist[i];
        const char *b=rec->bcd;
        char *o=str;
        *o++='A'; o=putu(o,rec->addr);
        *o++=' '; *o++='F'; *o++=(char)('0'+rec->func);
        *o++=' '; o=put(o,(rec->flags&RF_LBJ)?s+T_LBJ:s+T_NOLBJ);
        *o++=' '; *o++=(rec->flags&RF_ERR)?'!':'+';
        tiny(ROWY((uint8_t)(shown*2u)),o);
        o=str; uint8_t n=(uint8_t)(rec->len<32u?rec->len:32u);
        for(uint8_t k=0;k<n;k++) *o++=safe((uint8_t)b[k]);
        tiny(ROWY((uint8_t)(shown*2u+1u)),o);
    }
    counters(ROWY(6));
}

__attribute__((noinline))
static void draw(void){
    const app_api_t *A=g.A;
    char s[UI_SIZE] __attribute__((aligned(4)));
    A->asset_read(0,s,UI_SIZE);
    A->display_clear();
    A->status_clear();
    A->print_inverse(s+T_TITLE,2,0,true,true,(uint8_t)(2u+T_TITLE_CHARS*4u));
    A->draw_battery();
    const char *pg = g.page==0?s+T_SUM : s+T_PDU;
    A->print_inverse(pg,30,0,true,true,42u);

    if(g.page==0u) drawSummary(s); else drawPdus(s);

    char *f=str; uint32_t fr=A->rx_freq();
    f=putu(f,sub(&fr,100000u)); *f++='.';
    *f++=(char)('0'+sub(&fr,10000u)); *f++=(char)('0'+sub(&fr,1000u));
    *f++=(char)('0'+sub(&fr,100u)); *f++=(char)('0'+sub(&fr,10u));
    *f='\0';
    A->print_tiny(str,0,57,false,true);

    A->blit_status();
    A->blit_full();
}

/* ---- input ---- */
static void handleKeys(void){
    const app_api_t *A=g.A;
    uint8_t key=A->get_key();
    int d=A->nav_dir(key);
    if(d){
        int t = (g.page==0u) ? ((int)g.cur+d) : ((int)g.top+d);
        int hi = (g.page==0u) ? (int)g.count : (int)g.count;
        if(t<0) t=0;
        if(t>hi-1) t=hi-1;
        if(t<0) t=0;
        if(g.page==0u){ if((uint8_t)t!=g.cur){ g.cur=(uint8_t)t; g.redraw=1u; } }
        else if((uint8_t)t!=g.top){ g.top=(uint8_t)t; g.redraw=1u; }
    }
    if(key==APP_KEY_INVALID||key==g.prevKey){ g.prevKey=key; return; }
    g.prevKey=key;
    g.redraw=1u;
    switch(key){
        case APP_KEY_EXIT: g.running=false; break;
        case APP_KEY_1:    g.spk=!g.spk; A->audio_path(g.spk); break;
        case APP_KEY_2:    g.count=g.cur=g.top=0;
                           g.rx.syncs=g.rx.words=g.rx.ok=g.rx.fix=g.rx.bad=0;
                           g.rx.msgs=g.rx.up=g.rx.dn=0; break;
        case APP_KEY_3:    g.page^=1u; g.top=0; g.cur=0; break;
        default: break;
    }
}

/* ---- keys and screen, between frames ---- */
static void house(void){
    const app_api_t *A=g.A;
    handleKeys();
    if(!g.running) return;
    g.rssi=A->rssi_dbm();
    A->backlight_update();
    if(!g.redraw) return;
    g.redraw=0;
    adcRestore();
    A->battery_sample();
    adcSelPA4();
    draw();
}

__attribute__((noinline))
static void listen(void){
    memset(&g.dem,0,sizeof g.dem);
    g.dem.dc=BIAS_CODE; g.dem.hi=BIAS_CODE+100; g.dem.lo=BIAS_CODE-100;

    adcSelPA4();
    clkStart();
    uint32_t next=0;
    uint16_t cnt=0;
    g.redraw=1u;
    while(g.running){
        while((int32_t)(clkCyc()-next)<0){}
        next+=CYC_PER_SAMPLE;
        dem_sample(adcRead());
        if(++cnt<HOUSE_EVERY) continue;
        cnt=0;
        if(g.rx.inmsg && ++g.busyFor<BUSY_MAX) continue;   /* keep sampling a message */
        g.busyFor=0;
        house();
        next=clkCyc();
    }
    adcRestore();
}

__attribute__((section(".text.entry"),used))
void app_main(const app_api_t *api){
    rec_t recs[HISTORY];
    rec_t *hist[HISTORY];
    char text[40];
    for(uint8_t k=0;k<HISTORY;k++) hist[k]=&recs[k];
    g.A=api;
    g.hist=hist;
    g.text=text;
    g.prevKey=APP_KEY_INVALID;
    g.savedSqr3=ADC_SQR3; g.savedSmpr3=ADC_SMPR3;
    const uint32_t savedModer=GPIOA_MODER, savedDac=DAC_CR;
    const uint32_t savedRcc=RCC_APBENR1, savedDhr=DAC_DHR12R1;
    biasOn(savedModer,savedRcc);
    api->backlight_on();

    uint8_t cfg=0;
    api->cfg_load(&cfg,1);
    g.spk=(cfg&1u)!=0u;
    g.page=0;

    /* RAW RX: HPF/LPF, de-emphasis and AFC off (EPIRB 406); the loader restores
     * the registers through RADIO_SetupRegisters on exit. */
    api->bk_write(REG_2B,(uint16_t)((api->bk_read(REG_2B)|0x0700u)&~0x0007u));
    api->bk_write(REG_73,(uint16_t)(api->bk_read(REG_73)|0x0010u));
    api->audio_path(g.spk);
    api->set_af(APP_AF_FM);
    api->delay_ms(50);

    g.running=true;
    listen();

    biasOff(savedDac,savedDhr,savedRcc,savedModer);
    api->set_af(APP_AF_MUTE);
    api->audio_path(false);
    cfg=(uint8_t)(g.spk?1u:0u);
    api->cfg_save(&cfg,1);
}
