/* Copyright 2026 Armel F4HWN
 * https://github.com/armel
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * Tetris — compact overlay game for the 128x64 monochrome LCD.
 *
 * The 16x16 visible well fills the screen height down the left side; two hidden
 * spawn rows sit just above it.  Rather than solid walls, the well is framed by
 * short corner brackets and a floor line.  The narrow right-hand panel shows the
 * next piece, score, cleared lines, level and persistent best score.  Pieces
 * come from a shuffled seven-piece bag; a dotted ghost previews the landing.
 *
 * Keys: LEFT/RIGHT or 4/6 move, MENU or 2 rotates, 8 soft-drops,
 * STAR or 0 hard-drops, F pauses and EXIT quits.
 */

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>
#include "../app_api.h"
#include "tetris_assets.h"   /* generated by gen_assets.py */

#define W             128u
#define H              64u
#define COLS           16
#define VISIBLE_ROWS   16
#define HIDDEN_ROWS     2
#define ROWS            (VISIBLE_ROWS + HIDDEN_ROWS)
#define CELL            4
#define WELL_X          3       /* physical x of board column 0              */
#define WELL_Y          0       /* physical y of visible row 0 (full height) */
#define LABEL_X        72       /* left column shared by every panel label   */
#define PREVIEW_CX    108       /* centre of the NEXT-piece preview area      */
#define PREVIEW_CY     15
#define TICK_MS        20u
#define CFG_MAGIC  0x5445u

typedef struct {
    uint16_t magic;
    uint16_t version;
    uint32_t best;
} config_t;

/* All the state in one struct: Thumb-1 code then reaches every field from a
 * single base address (one literal per function instead of one per global),
 * byte fields first so their offsets fit ldrb's 0..31 immediate. */
struct globals {
    uint8_t previousKey, titleTick, level, bagPos, piece, nextPiece, rotation;
    bool running, title, bestDirty;
    /* cleared by new_game(), from paused to board */
    bool paused, gameOver, saverPaused, saverActive, newBest;
    uint16_t lines, gravityMs;
    uint32_t score;
    uint16_t board[ROWS];
    /* end of the new_game() block */
    uint16_t repeatMs;
    int32_t pieceX, pieceY;   /* words: loaded without a sign extension */
    uint32_t best;
    const app_api_t *api;
    uint8_t bag[7];
};
static struct globals g;
#define A (g.api)

_Static_assert(offsetof(struct globals, newBest) < 32u, "byte fields out of ldrb range");

/* GCC may lower aggregate clears to memset even for this freestanding blob. */
void *memset(void *dst, int value, size_t size)
{
    uint8_t *p = dst;
    while (size--)
        *p++ = (uint8_t)value;
    return dst;
}

/* Texts, piece masks, scoring, decimal places, wall kicks, the side panel
 * rows and the well frame are read-only assets (gen_assets.py), fetched from
 * external flash when needed. */

static void render(bool showPiece, uint32_t clearRows, uint8_t effect);
static void new_game(void);

/* -------------------------------------------------------------------------- */
/*  RNG and the shuffled 7-piece bag                                          */
/* -------------------------------------------------------------------------- */

/* 4x4 occupancy mask of a piece in a rotation (bit i = cell (i & 3, i >> 2)). */
static uint16_t mask_of(uint8_t type, uint8_t rot)
{
    uint16_t mask;
    A->asset_read(MASK + (type * 4u + (rot & 3u)) * 2u, &mask, sizeof(mask));
    return mask;
}

static void refill_bag(void)
{
    for (uint8_t i = 0; i < 7u; i++)
        g.bag[i] = i;
    for (uint8_t i = 6u; i > 0u; i--) {
        uint8_t j;
        do {
            j = (uint8_t)(A->rand32() >> 29);   /* resident PRNG, seeded by the loader */
        } while (j > i);
        const uint8_t t = g.bag[i]; g.bag[i] = g.bag[j]; g.bag[j] = t;
    }
    g.bagPos = 0;
}

static uint8_t take_piece(void)
{
    if (g.bagPos >= 7u)
        refill_bag();
    return g.bag[g.bagPos++];
}

/* -------------------------------------------------------------------------- */
/*  Framebuffer drawing: cells, pieces, side panel and dialogs                */
/* -------------------------------------------------------------------------- */

static void set_pixel(int x, int y)
{
    if ((unsigned)x >= W || (unsigned)y >= H)
        return;
    uint8_t *p;
    if (y < 8)
        p = &A->status_line[x];
    else
        p = &A->fb[(y >> 3) - 1][x];
    *p |= (uint8_t)(1u << (y & 7));
}

/* Corner brackets plus a solid floor — the well's frame, no vertical walls:
 * filled rectangles from the FRAME asset, in physical coordinates so they may
 * cross the status-line / framebuffer seam that A->draw_line cannot. */
static void container(void)
{
    uint8_t r[FRAME_LEN];
    A->asset_read(FRAME, r, sizeof(r));
    for (uint8_t i = 0; i < FRAME_LEN; i += 4u)
        for (int x = r[i]; x <= r[i + 2u]; x++)
            for (int y = r[i + 1u]; y <= r[i + 3u]; y++)
                set_pixel(x, y);
}

static void cell(int gx, int gy, uint8_t style)
{
    const int visibleY = gy - HIDDEN_ROWS;
    if ((unsigned)gx >= COLS || (unsigned)visibleY >= VISIBLE_ROWS)
        return;
    const int x = WELL_X + gx * CELL;
    const int y = WELL_Y + visibleY * CELL;
    if (style == 2u) {
        set_pixel(x, y + 1);
        set_pixel(x + 1, y);
        set_pixel(x + 2, y + 1);
        set_pixel(x + 1, y + 2);
    } else {
        const uint8_t size = style == 3u ? CELL : CELL - 1u;
        for (uint8_t dy = 0; dy < size; dy++)
            for (uint8_t dx = 0; dx < size; dx++)
                set_pixel(x + dx, y + dy);
    }
}

static bool collision(uint8_t type, uint8_t rot, int px, int py)
{
    const uint16_t mask = mask_of(type, rot);
    for (uint8_t i = 0; i < 16u; i++) {
        if (!(mask & (uint16_t)(1u << i)))
            continue;
        const int x = px + (i & 3u);
        const int y = py + (i >> 2);
        if (x < 0 || x >= COLS || y >= ROWS)
            return true;
        if (y >= 0 && (g.board[y] & (uint16_t)(1u << x)))
            return true;
    }
    return false;
}

static void draw_piece(uint8_t type, uint8_t rot, int px, int py, uint8_t style)
{
    const uint16_t mask = mask_of(type, rot);
    for (uint8_t i = 0; i < 16u; i++)
        if (mask & (uint16_t)(1u << i))
            cell(px + (i & 3u), py + (i >> 2), style);
}

/* `width` digits of value into buf, capped at the largest width-digit number
 * (no division: DECIMAL_PLACE holds 10^6 down to 1). */
static void number(char *buf, uint32_t value, uint8_t width)
{
    uint32_t place[DECIMAL_PLACE_LEN / 4u];
    A->asset_read(DECIMAL_PLACE, place, sizeof(place));
    const uint8_t first = (uint8_t)(7u - width);
    if (value >= place[first - 1u])
        value = place[first - 1u] - 1u;
    for (uint8_t i = 0; i < width; i++) {
        uint8_t digit = 0;
        while (value >= place[first + i]) {
            value -= place[first + i];
            digit++;
        }
        buf[i] = (char)('0' + digit);
    }
    buf[width] = 0;
}

static void preview(void)
{
    const uint16_t mask = mask_of(g.nextPiece, 0);
    const int ox = g.nextPiece < 2u ? PREVIEW_CX - 7 : PREVIEW_CX - 5;
    const int oy = g.nextPiece == 0u ? PREVIEW_CY - 5 : PREVIEW_CY - 3;
    for (uint8_t i = 0; i < 16u; i++) {
        if (!(mask & (uint16_t)(1u << i)))
            continue;
        const int x = ox + (i & 3u) * CELL;
        const int y = oy + (i >> 2) * CELL;
        for (uint8_t dy = 0; dy < CELL - 1u; dy++)
            for (uint8_t dx = 0; dx < CELL - 1u; dx++)
                set_pixel(x + dx, y + dy);
    }
}

static void panel(void)
{
    char buf[TEXT_MAX];
    uint8_t row[STAT_LEN];   /* per row: y (framebuffer row), value x, digits */
    const uint32_t value[4] = { g.score, g.lines, g.level, g.best };

    A->asset_read(T_NEXT, buf, TEXT_MAX);
    A->print_tiny(buf, LABEL_X, 2, false, true);
    preview();
    if (g.gameOver || g.paused) {
        const bool over = g.gameOver;
        A->asset_read(over ? (g.newBest ? T_NEW_BEST : T_GAME_OVER) : T_PAUSE, buf, TEXT_MAX);
        A->print_inverse(buf, over ? 82 : 90, 2, false, true, over ? 118 : 110);
    }

    /* "LABEL      value" rows; y is framebuffer-relative (physical y - 8),
     * the value right-aligned near the screen edge */
    A->asset_read(STAT, row, sizeof(row));
    for (uint8_t i = 0; i < 4u; i++) {
        const uint8_t *r = &row[i * 3u];
        A->asset_read(T_STAT + i * T_STAT_STRIDE, buf, TEXT_MAX);
        A->print_tiny(buf, LABEL_X, r[0], false, true);
        number(buf, value[i], r[2]);
        A->print_tiny(buf, r[1], r[0], false, true);
    }
}

/* effect 0 is normal, 1..8 is the line-clear sweep, 0xFF flashes a lock. */
static void render(bool showPiece, uint32_t clearRows, uint8_t effect)
{
    char buf[TEXT_MAX];
    A->display_clear();
    A->status_clear();
    A->asset_read(T_TETRIS, buf, TEXT_MAX);
    A->print_inverse(buf, 74, 0, true, true, 101);

    container();

    for (uint8_t y = 0; y < ROWS; y++)
        for (uint8_t x = 0; x < COLS; x++)
            if ((g.board[y] & (uint16_t)(1u << x)) && (!(clearRows & (1u << y)) ||
                (x >= effect && x < COLS - effect)))
                cell(x, y, 1u);

    if (showPiece && !g.gameOver) {
        int ghostY = g.pieceY;
        while (!collision(g.piece, g.rotation, g.pieceX, ghostY + 1))
            ghostY++;
        if (ghostY != g.pieceY)
            draw_piece(g.piece, g.rotation, g.pieceX, ghostY, 2u);
        draw_piece(g.piece, g.rotation, g.pieceX, g.pieceY, effect == 0xFFu ? 3u : 1u);
    }

    panel();
}

/* -------------------------------------------------------------------------- */
/*  Board mechanics: scoring, line clears, spawn, lock and moves              */
/* -------------------------------------------------------------------------- */

static void update_best(void)
{
    if (g.score > g.best) {
        g.best = g.score;
        g.bestDirty = true;
        g.newBest = true;
    }
}

static uint8_t clear_lines(void)
{
    uint32_t full = 0;
    uint8_t count = 0;
    for (uint8_t y = 0; y < ROWS; y++) {
        if (g.board[y] == 0xFFFFu) { full |= 1u << y; count++; }
    }
    if (!count)
        return 0;

    A->led(true);
    for (uint8_t step = 1u; step <= COLS / 2u; step++) {
        render(false, full, step);
        A->blit_status(); A->blit_full(); A->delay_ms(28);
    }
    A->led(false);

    int dst = ROWS - 1;
    for (int src = ROWS - 1; src >= 0; src--) {
        if (full & (1u << src))
            continue;
        if (dst != src)
            g.board[dst] = g.board[src];
        dst--;
    }
    while (dst >= 0) {
        g.board[dst] = 0;
        dst--;
    }
    return count;
}

static void spawn_piece(void)
{
    g.piece = g.nextPiece;
    g.nextPiece = take_piece();
    g.rotation = 0;
    g.pieceX = COLS / 2 - 2;
    g.pieceY = HIDDEN_ROWS - 1;
    if (collision(g.piece, g.rotation, g.pieceX, g.pieceY)) {
        g.gameOver = true;
        update_best();
    }
}

static void lock_piece(void)
{
    render(true, 0, 0xFFu);
    A->blit_status(); A->blit_full(); A->delay_ms(45);

    const uint16_t mask = mask_of(g.piece, g.rotation);
    bool above = false;
    for (uint8_t i = 0; i < 16u; i++) {
        if (!(mask & (uint16_t)(1u << i)))
            continue;
        const int x = g.pieceX + (i & 3u);
        const int y = g.pieceY + (i >> 2);
        if (y < HIDDEN_ROWS) above = true;
        else g.board[y] |= (uint16_t)(1u << x);
    }
    if (above) {
        g.gameOver = true;
        update_best();
        return;
    }

    const uint8_t cleared = clear_lines();
    g.lines = (uint16_t)(g.lines + cleared);
    while (g.level < 15u && g.lines >= (uint16_t)g.level * 10u)
        g.level++;
    uint16_t points;
    A->asset_read(LINE_POINTS + cleared * 2u, &points, sizeof(points));
    g.score += (uint32_t)points * g.level;
    update_best();
    spawn_piece();
}

static bool move_down(bool manual)
{
    if (!collision(g.piece, g.rotation, g.pieceX, g.pieceY + 1)) {
        g.pieceY++;
        if (manual) { g.score++; update_best(); }
        return true;
    }
    lock_piece();
    return false;
}

static void rotate_piece(void)
{
    const uint8_t next = (uint8_t)((g.rotation + 1u) & 3u);
    int8_t kick[KICK_LEN];
    A->asset_read(KICK, kick, sizeof(kick));
    for (uint8_t i = 0; i < 5u; i++)
        if (!collision(g.piece, next, g.pieceX + kick[i], g.pieceY)) {
            g.pieceX += kick[i]; g.rotation = next; return;
        }
    if (!collision(g.piece, next, g.pieceX, g.pieceY - 1)) {
        g.pieceY--; g.rotation = next;
    }
}

static void hard_drop(void)
{
    uint8_t distance = 0;
    while (!collision(g.piece, g.rotation, g.pieceX, g.pieceY + 1)) {
        g.pieceY++; distance++;
    }
    g.score += (uint32_t)distance * 2u;
    update_best();
    lock_piece();
}

/* -------------------------------------------------------------------------- */
/*  Input, screensaver handling and the main loop                            */
/* -------------------------------------------------------------------------- */

/* Title: the 1 KiB picture is streamed from the assets into the LCD buffers,
 * with a blinking prompt on the blank bottom page. */
static void draw_title(void)
{
    g.titleTick++;
    A->asset_read(ART_TITLE, A->status_line, W);
    A->asset_read(ART_TITLE + W, A->fb[0], 7u * W);
    if (g.titleTick & 32u) {
        char buf[TEXT_MAX];
        A->asset_read(T_PRESS, buf, TEXT_MAX);
        A->print_bold(buf, 0, W - 1, 6);
    }
}

static void key_action(uint8_t key, bool repeat)
{
    if (key == APP_KEY_EXIT) { g.running = false; return; }
    if (g.title || g.gameOver) {   /* the game-over restart keys also leave the title */
        if (!repeat && (key == APP_KEY_MENU || key == APP_KEY_STAR || key == APP_KEY_0)) {
            g.title = false;
            new_game();
        }
        return;
    }
    if (!repeat && key == APP_KEY_F) { g.paused = !g.paused; return; }
    if (g.paused)
        return;

    int direction = 0;
    if (key == APP_KEY_4) direction = -1;
    else if (key == APP_KEY_6) direction = 1;
    else if (key == APP_KEY_UP || key == APP_KEY_DOWN) direction = A->nav_dir(key);
    if (direction) {
        if (!collision(g.piece, g.rotation, g.pieceX + direction, g.pieceY))
            g.pieceX += direction;
        return;
    }
    if (key == APP_KEY_8) { move_down(true); return; }
    if (repeat)
        return;
    if (key == APP_KEY_MENU || key == APP_KEY_2) rotate_piece();
    else if (key == APP_KEY_STAR || key == APP_KEY_0) hard_drop();
}

static void poll_key(void)
{
    uint8_t key = A->get_key();
    if (key == APP_KEY_SAVER) {
        if (!g.paused && !g.gameOver) { g.paused = true; g.saverPaused = true; }
        g.saverActive = true;
        g.previousKey = APP_KEY_INVALID;
        g.repeatMs = 0;
        return;
    }
    if (key == APP_KEY_WAKE || key == APP_KEY_PTT) {
        if (g.saverPaused) g.paused = false;
        g.saverPaused = false;
        g.saverActive = false;
        key = APP_KEY_INVALID;
    }
    if (key == APP_KEY_INVALID) {
        g.previousKey = key;
        g.repeatMs = 0;
        return;
    }
    if (key != g.previousKey) {
        key_action(key, false);
        g.repeatMs = 260u;
    } else if (g.repeatMs > TICK_MS) {
        g.repeatMs -= TICK_MS;
    } else {
        key_action(key, true);
        g.repeatMs = 80u;
    }
    g.previousKey = key;
}

static void new_game(void)
{
    /* paused, gameOver, saverPaused, saverActive, newBest, lines, gravityMs,
       score and the board, all cleared at once */
    memset((uint8_t *)&g + offsetof(struct globals, paused), 0,
           offsetof(struct globals, board) + sizeof(g.board)
           - offsetof(struct globals, paused));
    g.level = 1;
    g.bagPos = 7;
    g.nextPiece = take_piece();
    spawn_piece();
}

__attribute__((section(".text.entry"), used))
void app_main(const app_api_t *api)
{
    config_t cfg;
    A = api;
    A->cfg_load((uint8_t *)&cfg, sizeof(cfg));
    g.best = cfg.magic == CFG_MAGIC && cfg.version == 1u ? cfg.best : 0u;

    g.previousKey = APP_KEY_INVALID;
    g.running = true;   /* the rest of g starts zeroed (.bss) */
    A->led(false);
    A->backlight_on();
    new_game();
    g.title = true;

    while (g.running) {
        poll_key();
        if (!g.running)
            break;

        if (!g.saverActive) {   /* the saver freezes the game */
            if (!g.title && !g.paused && !g.gameOver) {
                const uint16_t interval = g.level >= 15u ? 100u : (uint16_t)(900u - (g.level - 1u) * 55u);
                g.gravityMs = (uint16_t)(g.gravityMs + TICK_MS);
                if (g.gravityMs >= interval) {
                    g.gravityMs = 0;
                    move_down(false);
                }
            }

            if (g.title) draw_title();
            else render(true, 0, 0);
            A->blit_status();
            A->blit_full();
        }
        A->backlight_update();
        A->delay_ms(TICK_MS);
    }

    update_best();
    if (g.bestDirty) {
        cfg.magic = CFG_MAGIC;
        cfg.version = 1u;
        cfg.best = g.best;
        A->cfg_save((const uint8_t *)&cfg, sizeof(cfg));
    }
    A->led(false);
}
