/* GB2312 submenu values. Generated by docs/font/_gen_menu_cn.py */
#include "ui/menu_sub_values_cn.h"
#include "settings.h"

const char gSubMenu_LANGUAGE_EN[][8] = {
    "English",
    "Chinese",
};

const char gSubMenu_LANGUAGE_CN[][8] = {
    "\xD3\xA2\xCE\xC4",
    "\xD6\xD0\xCE\xC4",
};

const char gSubMenu_OFF_ON_CN[][4] = {
    "\xB9\xD8", "\xBF\xAA",
};

const char gSubMenu_SFT_D_CN[][4] = {
    "\xCE\xDE", "+", "-",
};

const char gSubMenu_W_N_CN[][7] = {
    "\xBF\xED\xB4\xF8", "\xD5\xAD\xB4\xF8",
};

const char *const gSubMenu_RXMode_CN[] = {
    "\xBD\xF6\xD6\xF7\xD0\xC5\xB5\xC0", "\xCB\xAB\xC6\xB5\xCA\xD8\xBA\xF2", "\xBF\xE7\xB6\xCE", "\xD6\xF7\xB7\xA2\xCB\xAB\xCA\xD5",
};

const char *const gSubMenu_MDF_CN[] = {
    "\xC6\xB5\xC2\xCA", "\xD0\xC5\xB5\xC0\xBA\xC5", "\xC3\xFB\xB3\xC6", "\xC3\xFB\xB3\xC6\x2B\xC6\xB5\xC2\xCA",
};

const char *const gSubMenu_PTT_ID_CN[] = {
    "\xB9\xD8", "\xC9\xCF\xD0\xD0\xC2\xEB", "\xCF\xC2\xD0\xD0\xC2\xEB", "\xC9\xCF\x2B\xCF\xC2\xD0\xD0\xC2\xEB",
    "APOLLO\nQUINDAR",
};

const char gSubMenu_PONMSG_CN[][10] = {
    "\xB9\xD8\xB1\xD5", "\xC4\xAC\xC8\xCF", "\xD7\xD4\xB6\xA8\xD2\xE5",
};

const char gSubMenu_ROGER_CN[][8] = {
    "\xB9\xD8", "ROGER", "MDC", YAN_ID_NAME,
};

const char gSubMenu_RESET_CN[][8] = {
    "VFO", "\xC8\xAB\xB2\xBF",
};

const char gSubMenu_RX_TX_CN[][16] = {
    "\xB9\xD8", "\xB7\xA2\xC9\xE4", "\xBD\xD3\xCA\xD5", "\xBD\xD3\xCA\xD5\x2F\xB7\xA2\xC9\xE4",
};

const char gSubMenu_BAT_TXT_CN[][10] = {
    "\xCE\xDE", "\xB5\xE7\xD1\xB9", "\xB0\xD9\xB7\xD6\xB1\xC8",
};

const char gSubMenu_SET_NAV_CN[][17] = {
    "\xD7\xF3\n\xD3\xD2\nUV-K1(8)",
    "\xC9\xCF\n\xCF\xC2\nUV-K5(6)",
};

const char gSubMenu_VOICE_CN[][4] = {
    "\xB9\xD8", "\xD6\xD0", "\xD3\xA2",
};

const char gSubMenu_AL_MOD_CN[][5] = {
    "\xCF\xD6\xB3\xA1", "\xD2\xF4\xB5\xF7",
};

const char gSubMenu_D_RSP_CN[][11] = {
    "\xCE\xDE\xB6\xAF\xD7\xF7", "\xCF\xEC\xC1\xE5", "\xBB\xD8\xB8\xB4", "\xCB\xAB\xB6\xCB",
};

const char gSubMenu_TXP_CN[][6] = {
    "\xD3\xC3\xBB\xA7", "LOW 1", "LOW 2", "LOW 3", "LOW 4", "LOW 5", "MID", "HIGH",
};

const char gSubMenu_SET_PTT_CN[][8] = {
    "\xBE\xAD\xB5\xE4", "\xD2\xBB\xBC\xFC",
};

const char gSubMenu_SET_TOT_CN[][7] = {
    "\xB9\xD8", "\xC9\xF9\xD2\xF4", "\xCA\xD3\xBE\xF5", "\xC8\xAB\xB2\xBF",
};

const char gSubMenu_SET_LCK_CN[][20] = {
    "\xBD\xF6\xBC\xFC\xC5\xCC",
    "\xBC\xFC\xC5\xCC\n\xB6\xAF\xD7\xF7",
    "\xBC\xFC\xC5\xCC\nPTT",
    "\xBC\xFC\xC5\xCC\n\xB6\xAF\xD7\xF7\nPTT",
};

const char gSubMenu_SET_MET_CN[][8] = {
    "\xBE\xAB\xBC\xF2", "\xBE\xAD\xB5\xE4",
};

const char gSubMenu_SET_NFM_CN[][16] = {
    "\xD5\xAD\xB4\xF8", "\xB8\xFC\xD5\xAD",
};

const char gSubMenu_SET_KEY_CN[][16] = {
    "MENU\xBC\xFC", "\xC9\xCF\xBC\xFC", "\xCF\xC2\xBC\xFC", "EXIT\xBC\xFC", "*\xBC\xFC",
};

const char gSubMenu_SET_SCN_CN[][8] = {
    "\xD5\xFD\xB3\xA3", "\xBF\xEC\xCB\xD9",
};

const char gSubMenu_SURE_CN[] = "\xC8\xB7\xC8\xCF\x3F";
const char gSubMenu_WAIT_CN[] = "\xC7\xEB\xB5\xC8\xB4\xFD\x21";
const char gSubMenu_SC_REV_STOP_CN[] = "\xCD\xA3\xD6\xB9";
const char gSubMenu_ABR_ON_CN[] = "\xBF\xAA";
const char gSubMenu_LIST_CN_OFF[] = "\xB9\xD8";
const char gSubMenu_LIST_CN_ALL[] = "\xC8\xAB\xB2\xBF";
const char gSubMenu_MEM_NONE_CN[] = "\xCE\xDE";
