/* GB2312 menu titles. Generated by docs/font/_gen_menu_cn.py */
#include <stddef.h>
#include "settings.h"
#include "ui/menu.h"

const char *UI_MENU_GetMenuTitle(const t_menu_item *item)
{
    if (item == NULL)
        return "";
    if (gUiLanguage != UI_LANGUAGE_CN)
        return item->name;

    switch (item->menu_id)
    {
    case MENU_LANGUAGE: return "\xD3\xEF\xD1\xD4";
    case MENU_STEP: return "\xB2\xBD\xBD\xF8";
    case MENU_TXP: return "\xB9\xA6\xC2\xCA";
    case MENU_R_DCS: return "\xBD\xD3\xCA\xD5\xCA\xFD\xD7\xD6\xD1\xC7\xD2\xF4";
    case MENU_R_CTCS: return "\xBD\xD3\xCA\xD5\xC4\xA3\xC4\xE2\xD1\xC7\xD2\xF4";
    case MENU_T_DCS: return "\xB7\xA2\xC9\xE4\xCA\xFD\xD7\xD6\xD1\xC7\xD2\xF4";
    case MENU_T_CTCS: return "\xB7\xA2\xC9\xE4\xC4\xA3\xC4\xE2\xD1\xC7\xD2\xF4";
    case MENU_SFT_D: return "\xC6\xB5\xB2\xEE\xB7\xBD\xCF\xF2";
    case MENU_OFFSET: return "\xC6\xB5\xB2\xEE\xC6\xB5\xC2\xCA";
    case MENU_W_N: return "\xBF\xED\xD5\xAD\xB4\xF8";
#ifndef ENABLE_FEAT_F4HWN
    case MENU_SCR: return "\xB8\xC9\xC8\xC5\xBC\xD3\xC3\xDC";
#endif
    case MENU_BCL: return "\xB7\xB1\xC3\xA6\xCB\xF8\xB6\xA8";
    case MENU_COMPAND: return "\xD3\xEF\xD2\xF4\xD1\xB9\xC0\xA9";
    case MENU_AM: return "\xB5\xF7\xD6\xC6\xC4\xA3\xCA\xBD";
#ifdef ENABLE_FEAT_F4HWN
    case MENU_TX_LOCK: return "\xB7\xA2\xC9\xE4\xCB\xF8";
#endif
    case MENU_LIST_CH: return "\xD0\xC5\xB5\xC0\xC1\xD0\xB1\xED";
    case MENU_MEM_CH: return "\xB4\xE6\xD0\xC5\xB5\xC0";
    case MENU_DEL_CH: return "\xC9\xBE\xD0\xC5\xB5\xC0";
    case MENU_MEM_NAME: return "\xC3\xFC\xC3\xFB\xD0\xC5\xB5\xC0";
    case MENU_MDF: return "\xD0\xC5\xB5\xC0\xCF\xD4\xCA\xBE";
    case MENU_S_LIST: return "\xC9\xA8\xC3\xE8\xC1\xD0\xB1\xED";
    case MENU_S_PRI: return "\xD3\xC5\xCF\xC8\xC9\xA8\xC3\xE8";
    case MENU_S_PRI_CH_1: return "\xD3\xC5\xCF\xC8\xD0\xC5\xB5\xC0\x31";
    case MENU_S_PRI_CH_2: return "\xD3\xC5\xCF\xC8\xD0\xC5\xB5\xC0\x32";
    case MENU_SC_REV: return "\xC9\xA8\xC3\xE8\xBB\xD6\xB8\xB4";
    case MENU_SQL: return "\xBE\xB2\xD4\xEB";
    case MENU_F1SHRT: return "\xB2\xE0\xBC\xFC\x31\xB6\xCC\xB0\xB4";
    case MENU_F1LONG: return "\xB2\xE0\xBC\xFC\x31\xB3\xA4\xB0\xB4";
    case MENU_F2SHRT: return "\xB2\xE0\xBC\xFC\x32\xB6\xCC\xB0\xB4";
    case MENU_F2LONG: return "\xB2\xE0\xBC\xFC\x32\xB3\xA4\xB0\xB4";
    case MENU_MLONG: return "\x4D\x45\x4E\x55\xB3\xA4\xB0\xB4";
    case MENU_AUTOLK: return "\xD7\xD4\xB6\xAF\xCB\xF8\xBC\xFC";
#ifdef ENABLE_FEAT_F4HWN
    case MENU_SET_LCK: return "\xCB\xF8\xBC\xFC\xB7\xB6\xCE\xA7";
#endif
    case MENU_TDR: return "\xBD\xD3\xCA\xD5\xC4\xA3\xCA\xBD";
    case MENU_TOT: return "\xB7\xA2\xC9\xE4\xCF\xDE\xCA\xB1";
    case MENU_SAVE: return "\xCA\xA1\xB5\xE7\xC4\xA3\xCA\xBD";
    case MENU_BAT_TXT: return "\xB5\xE7\xB3\xD8\xCF\xD4\xCA\xBE";
    case MENU_MIC: return "\xC2\xF3\xBF\xCB\xB7\xE7\xD4\xF6\xD2\xE6";
    case MENU_PONMSG: return "\xBF\xAA\xBB\xFA\xBB\xAD\xC3\xE6";
    case MENU_ABR: return "\xB1\xB3\xB9\xE2\xCA\xB1\xBC\xE4";
    case MENU_ABR_MIN: return "\xB1\xB3\xB9\xE2\xD7\xEE\xB0\xB5";
    case MENU_ABR_MAX: return "\xB1\xB3\xB9\xE2\xD7\xEE\xC1\xC1";
    case MENU_ABR_ON_TX_RX: return "\xCA\xD5\xB7\xA2\xB1\xB3\xB9\xE2";
    case MENU_BEEP: return "\xB0\xB4\xBC\xFC\xD2\xF4";
#ifdef ENABLE_VOICE
    case MENU_VOICE: return "\xD3\xEF\xD2\xF4";
#endif
    case MENU_ROGER: return "\xB7\xA2\xC9\xE4\xCE\xB2\xD2\xF4";
    case MENU_STE: return "\xCE\xB2\xD2\xF4\xCF\xFB\xB3\xFD";
    case MENU_RP_STE: return "\xB9\xFD\xD6\xD0\xBC\xCC\xCE\xB2\xD2\xF4\xCF\xFB\xB3\xFD";
    case MENU_1_CALL: return "\xB0\xB4\xBC\xFC\xBC\xB4\xBA\xF4";
#ifdef ENABLE_ALARM
    case MENU_AL_MOD: return "\xB1\xA8\xBE\xAF";
#endif
#ifdef ENABLE_DTMF_CALLING
    case MENU_ANI_ID: return "ANI ID";
#endif
    case MENU_UPCODE: return "\xC9\xCF\xD0\xD0\xC2\xEB";
    case MENU_DWCODE: return "\xCF\xC2\xD0\xD0\xC2\xEB";
    case MENU_PTT_ID: return "PTT ID";
    case MENU_D_ST: return "DTMF ST";
#ifdef ENABLE_DTMF_CALLING
    case MENU_D_RSP: return "\x44\x54\x4D\x46\xCF\xEC\xD3\xA6";
    case MENU_D_HOLD: return "\x44\x54\x4D\x46\xB1\xA3\xB3\xD6";
#endif
    case MENU_D_PRE: return "\x44\x54\x4D\x46\xC7\xB0\xB5\xBC";
#ifdef ENABLE_DTMF_CALLING
    case MENU_D_DCD: return "\x44\x54\x4D\x46\xBD\xE2\xC2\xEB";
    case MENU_D_LIST: return "\x44\x54\x4D\x46\xC1\xAA\xCF\xB5\xC8\xCB";
#endif
    case MENU_D_LIVE_DEC: return "\x44\x54\x4D\x46\xCF\xD4\xCA\xBE";
#if !defined(ENABLE_FEAT_F4HWN) && defined(ENABLE_AM_FIX)
    case MENU_AM_FIX: return "AM Fix";
#endif
    case MENU_VOX: return "\xC9\xF9\xBF\xD8";
    case MENU_VOL: return "\xCF\xB5\xCD\xB3\xD0\xC5\xCF\xA2";
    case MENU_MIC_BAR: return "\xB7\xA2\xC9\xE4\xCC\xF5";
#ifdef ENABLE_FEAT_F4HWN
    case MENU_SET_PWR: return "\xC9\xE8\xD6\xC3\xB9\xA6\xC2\xCA";
    case MENU_SET_PTT: return "\xC9\xE8\xD6\xC3\x50\x54\x54";
    case MENU_SET_TOT: return "\xC9\xE8\xD6\xC3\x54\x4F\x54";
    case MENU_SET_EOT: return "\xC9\xE8\xD6\xC3\x45\x4F\x54";
    case MENU_SET_CTR: return "\xC9\xE8\xD6\xC3\xB6\xD4\xB1\xC8\xB6\xC8";
    case MENU_SET_INV: return "\xC9\xE8\xD6\xC3\xB7\xB4\xC9\xAB";
#ifdef ENABLE_FEAT_F4HWN_AUDIO
    case MENU_SET_AUD: return "\xD2\xF4\xC6\xB5\xD4\xA4\xC9\xE8";
#endif
    case MENU_SET_TMR: return "\xC9\xE8\xD6\xC3\xB6\xA8\xCA\xB1";
#ifdef ENABLE_FEAT_F4HWN_SLEEP
    case MENU_SET_OFF: return "\xBD\xF8\xC8\xEB\xD0\xDD\xC3\xDF";
#endif
#ifdef ENABLE_FEAT_F4HWN_NARROWER
    case MENU_SET_NFM: return "\xC9\xE8\xD6\xC3\xD5\xAD\xB4\xF8";
#endif
#ifdef ENABLE_FEAT_F4HWN_VOL
    case MENU_SET_VOL: return "\xC9\xE8\xD6\xC3\xD2\xF4\xC1\xBF";
#endif
#ifdef ENABLE_FEAT_F4HWN_RESCUE_OPS
    case MENU_SET_KEY: return "\xC9\xE8\xD6\xC3\xB0\xB4\xBC\xFC";
#endif
#ifdef ENABLE_NOAA
    case MENU_NOAA_S: return "\xC9\xE8\x4E\x57\x52";
#endif
#ifdef ENABLE_FEAT_F4HWN_SCAN_FASTER
    case MENU_SET_SCN: return "\xC9\xE8\xD6\xC3\xC9\xA8\xC3\xE8";
#endif
#ifdef ENABLE_FEAT_F4HWN_LOGO_SAV
    case MENU_SET_SAV: return "\xC9\xE8\xD6\xC3\xB1\xA3\xB4\xE6";
#endif
    case MENU_SET_MET: return "\xC9\xE8\xD6\xC3\xD2\xC7\xB1\xED";
    case MENU_SET_GUI: return "\xC9\xE8\xD6\xC3\x47\x55\x49";
    case MENU_SET_NAV: return "\xB5\xBC\xBA\xBD\xBC\xFC";
#endif
    case MENU_F_LOCK: return "\xCB\xF8\xB6\xA8\xC6\xB5\xB6\xCE";
#ifndef ENABLE_FEAT_F4HWN
    case MENU_200TX: return "Tx200";
    case MENU_350TX: return "Tx350";
    case MENU_500TX: return "Tx500";
    case MENU_SCREN: return "\xBC\xD3\xC3\xDC\xC6\xF4\xD3\xC3";
#endif
    case MENU_350EN: return "\x33\x35\x30\xC6\xF4\xD3\xC3";
#ifdef ENABLE_F_CAL_MENU
    case MENU_F_CALI: return "\xC6\xB5\xC2\xCA\xD0\xA3\xD7\xBC";
#endif
    case MENU_BATCAL: return "\xB5\xE7\xB3\xD8\xD0\xA3\xD7\xBC";
    case MENU_BATTYP: return "\xB5\xE7\xB3\xD8\xC0\xE0\xD0\xCD";
#ifndef ENABLE_FEAT_F4HWN
    case MENU_SET_NAV: return "\xB5\xBC\xBA\xBD\xBC\xFC";
#endif
    case MENU_RESET: return "\xBB\xD6\xB8\xB4\xB3\xF6\xB3\xA7";
#ifdef ENABLE_MESSENGER
    case MENU_MSG_RX:   return "\xD0\xC5\xCF\xA2\xBD\xD3\xCA\xD5";                 /* 信息接收 */
    case MENU_MSG_CSG:  return "\xD0\xC5\xCF\xA2\xB1\xBE\xBB\xFA\xC3\xFB\xB3\xC6"; /* 信息本机名称 */
    case MENU_MSG_ACK:  return "\xD0\xC5\xCF\xA2\xD3\xA6\xB4\xF0";                 /* 信息应答 */
    case MENU_MSG_BEEP: return "\xD0\xC5\xCF\xA2\xBD\xD3\xCA\xD5\xD2\xF4";         /* 信息接收音 */
    case MENU_MSG_LED:  return "\xD0\xC5\xCF\xA2\xBD\xD3\xCA\xD5\xB5\xC6\xB9\xE2"; /* 信息接收灯光 */
    case MENU_RNG_RSP:  return "\xD0\xC5\xCF\xA2\xB7\xB6\xCE\xA7\xBB\xD8\xD3\xA6"; /* 信息范围回应 */
#endif
    default:
        return item->name;
    }
}

const char *UI_MENU_GetHeaderTitle(void)
{
    if (gUiLanguage == UI_LANGUAGE_CN)
        return "\xB2\xCB\xB5\xA5";
    return "menu";
}

const char *UI_MENU_GetSideFunctionName(uint8_t index)
{
    if (index >= gSubMenu_SIDEFUNCTIONS_size)
        return "";
    if (gUiLanguage != UI_LANGUAGE_CN)
        return gSubMenu_SIDEFUNCTIONS[index].name;

    switch (gSubMenu_SIDEFUNCTIONS[index].id)
    {
    case ACTION_OPT_NONE: return "\xCE\xDE";
    case ACTION_OPT_FLASHLIGHT: return "\xCA\xD6\xB5\xE7";
    case ACTION_OPT_POWER: return "\xB9\xA6\xC2\xCA";
    case ACTION_OPT_MONITOR: return "\xBC\xE0\xCC\xFD";
    case ACTION_OPT_SCAN: return "\xC9\xA8\xC3\xE8";
    case ACTION_OPT_VOX: return "\xC9\xF9\xBF\xD8";
    case ACTION_OPT_ALARM: return "\xB1\xA8\xBE\xAF";
    case ACTION_OPT_FM: return "\xCA\xD5\xD2\xF4\xBB\xFA";
    case ACTION_OPT_1750: return "1750Hz";
    case ACTION_OPT_KEYLOCK: return "\xCB\xF8\xBC\xFC\xC5\xCC";
    case ACTION_OPT_A_B: return "\x41\x2F\x42\xD0\xC5\xB5\xC0";
    case ACTION_OPT_VFO_MR: return "VFO\n\xD0\xC5\xB5\xC0";
    case ACTION_OPT_SWITCH_DEMODUL: return "\xB5\xF7\xD6\xC6";
    case ACTION_OPT_BLMIN_TMP_OFF: return "\xB1\xB3\xB9\xE2\xC1\xD9\xCA\xB1\xB9\xD8";
#ifdef ENABLE_FEAT_F4HWN
    case ACTION_OPT_RXMODE: return "\xBD\xD3\xCA\xD5\xC4\xA3\xCA\xBD";
    case ACTION_OPT_MAINONLY: return "\xBD\xF6\xD6\xF7\xD0\xC5\xB5\xC0";
    case ACTION_OPT_PTT: return "PTT";
    case ACTION_OPT_WN: return "\xBF\xED\n\xD5\xAD";
    case ACTION_OPT_MUTE: return "\xBE\xB2\xD2\xF4";
    case ACTION_OPT_RXA: return "RxA";
#ifdef ENABLE_FEAT_F4HWN_RESCUE_OPS
    case ACTION_OPT_POWER_HIGH: return "\xB9\xA6\xC2\xCA\n\xB8\xDF";
    case ACTION_OPT_REMOVE_OFFSET: return "\xD2\xC6\xB3\xFD\n\xC6\xB5\xB2\xEE";
#endif
#endif
    default:
        return gSubMenu_SIDEFUNCTIONS[index].name;
    }
}

