/* Copyright 2026
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * ACARS RX (development build) - receives ACARS (ARINC 618: 131.525 MHz AM,
 * MSK 2400 baud, 1200/2400 Hz tones, LSB-first bytes with odd parity in bit 7)
 * and shows the decoded message. Reference: acarsdec msk.c / acars.c (Thierry
 * Leconte); the demodulator below is a fixed-point transcription of its DSP and
 * was validated against its test.wav (7 real messages, 4 channels).
 *
 * The BK4819 has no ACARS/MSK demodulator, so as LBJ RX / APRS RX / EPIRB 406
 * do, the RX audio reaches PA4 (voice DAC pin, held at mid-scale by the MCU DAC)
 * and is sampled on ADC channel 4 at 19.2 kHz (8 samples per 2400-baud bit),
 * timed from SysTick, continuously. The receiver is switched to RAW (RX HPF/LPF,
 * de-emphasis and AFC off) and to AM.
 *
 * Demodulator (why it is shaped this way):
 *   - the audio is real, so the complex baseband is made by multiplying every
 *     sample with exp(-j p) of a LO at 1800 Hz - the middle of the two tones.
 *     1800/19200 = 3/32 turn per sample, and the matched filter wants
 *     cos(2*pi*(i-8)/32): both are values of the SAME 64-entry Q12 cosine table
 *     (sin(x) = cos(x-90deg)), so 128 B of flash carry the whole DSP.
 *   - a bit clock runs off the VCO phase (3/4 turn = exactly 8 samples); once
 *     per bit the last FLEN=17 baseband samples (two bit periods) are correlated
 *     with that cosine window.
 *   - the decision is a plain sign test on the alternating Re/Im component
 *     (MSK is OQPSK), so no level threshold has to be tracked and long runs of
 *     equal bits cannot drag the slicer (the failure mode of a delay-multiply
 *     demodulator on real signals).
 *   - a bang-bang carrier PLL (+-2/4096 turn per sample) locks the LO phase on
 *     the preamble through the quadrature component.
 * Frames: SYN SYN SOH txt... ETX/ETB crc_lo crc_hi; CRC-16/KERMIT (0x8408,
 * reflected, init 0) over txt+CRC must be 0. The burst polarity is recovered
 * from SYN vs ~SYN and folded into the demodulator's quadrature counter, which
 * inverts the whole bit stream (CRC bytes included).
 *
 * Keys: 1 speaker; 4 backlight always-on; UP/DOWN scroll the message text;
 * EXIT quit. A decode blinks the green LED (on/off/on/off, 100 ms a step - the
 * same 100 ms "on" the radio's own RX-end blink uses) and wakes the backlight.
 * The footer shows the key state, the number of messages received and the live
 * RSSI; the frequency is on the status bar. Tune the VFO to 131.525 MHz AM
 * manually (129.525 / 136.975 also carry ACARS).
 */

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>
#include "../app_api.h"
#include "acr_assets.h"       /* generated by gen_assets.py */

/* ---- MCU registers (PY32F071, core and SysTick at 48 MHz, 10 ms period) ---- */
static inline volatile uint32_t *hw(uint32_t a){
    volatile uint32_t *p=(volatile uint32_t *)a;
    __asm__("" : "+l"(p));
    return p;
}
#define SYST_LOAD   (*(volatile uint32_t *)0xE000E014u)
#define SYST_VAL    (*(volatile uint32_t *)0xE000E018u)
#define ADC_SR      (hw(0x40012400u)[0x00/4])
#define ADC_CR2     (hw(0x40012400u)[0x08/4])
#define ADC_SMPR3   (hw(0x40012400u)[0x14/4])
#define ADC_SQR3    (hw(0x40012400u)[0x38/4])
#define ADC_DR      (hw(0x40012400u)[0x50/4])
#define GPIOA_MODER (*(volatile uint32_t *)0x50000000u)
#define DAC_CR      (hw(0x40007400u)[0x00/4])
#define DAC_SWTRIGR (hw(0x40007400u)[0x04/4])
#define DAC_DHR12R1 (hw(0x40007400u)[0x08/4])
#define RCC_APBENR1 (*(volatile uint32_t *)0x4002103Cu)
#define RCC_DACEN   (1u << 29)
#define DAC_CR_BIAS ((1u << 0) | (1u << 1) | (1u << 2) | (7u << 3))
#define BIAS_CODE   2048u
#define ADC_SR_EOC     (1u << 1)
#define ADC_CR2_START  ((1u << 22) | (1u << 20))
#define SMP8_POS       24u
#define SMP4_POS       12u
#define ADC_CH_PA4     4u
#define FS             19200u
#define CYC_PER_SAMPLE (48000000u / FS)
#define HOUSE_EVERY    960u    /* samples between key/screen slots (50 ms) */
#define LED_EVERY      1920u   /* samples per green-LED blink step (100 ms) */
#define BUSY_MAX       100u    /* serve keys anyway after 5 s inside a frame */

#define REG_2B  0x2Bu          /* RX HPF/LPF + de-emphasis + AFC (EPIRB 406 RAW) */
#define REG_73  0x73u

/* ---- demodulator (test/fx.py, class FxDemod; this is a transcription) ---- */
#define ACR_FLEN   17u         /* matched-filter length: INTRATE/1200 + 1      */
#define ACR_STEP   384         /* 1800 Hz at 19.2 kHz, in 1/4096 turn          */
#define ACR_CLKTHR 3072        /* 3/4 turn -> one bit every 8 samples          */
#define ACR_PLLMAX 1           /* bang-bang carrier PLL step, in 1/4096 turn   */
#define ACR_DCSH   8           /* audio DC tracker (carrier level) shift       */
#define ACR_MSGMAX 240u        /* ACARS text limit (acarsdec aborts past 240)  */

/* AF output modes the WAIT screen's key 2 cycles through, for on-air bring-up:
 * FM (1, what this firmware's own AM path and every RX app use), AM (7),
 * BASEBAND1/RAW (4), BASEBAND2/USB (5). The mode that makes the trace line show
 * 16 01 (2nd SYN + SOH) is the right one. */
static const uint8_t AF_CYCLE[]={1u,7u,4u,5u};
#define AF_CYCLE_N (sizeof AF_CYCLE / sizeof AF_CYCLE[0])

/* Q12 cosine, one period: T[i] = round(4096*cos(2*pi*i/64)). The matched filter
 * taps are T[(2*(i-8)) & 63] and the LO is (T[i], -T[i+16]) = (cos p, sin p). */
static const int16_t ACR_T[64] = {
     4096,  4076,  4017,  3920,  3784,  3612,  3406,  3166,
     2896,  2598,  2276,  1931,  1567,  1189,   799,   401,
        0,  -401,  -799, -1189, -1567, -1931, -2276, -2598,
    -2896, -3166, -3406, -3612, -3784, -3920, -4017, -4076,
    -4096, -4076, -4017, -3920, -3784, -3612, -3406, -3166,
    -2896, -2598, -2276, -1931, -1567, -1189,  -799,  -401,
        0,   401,   799,  1189,  1567,  1931,  2276,  2598,
     2896,  3166,  3406,  3612,  3784,  3920,  4017,  4076,
};

typedef struct {
    /* demodulator */
    int32_t  dc, acc, clk;         /* audio DC, LO phase, bit clock (1/4096)   */
    int16_t  ring[2u * ACR_FLEN];  /* complex baseband ring                    */
    uint8_t  idx, msks;            /* ring write index, MSK quadrature counter */
    int8_t   corr;                 /* carrier PLL frequency correction         */
    /* frame assembler */
    uint8_t  st, n, ob, c0, len, tlen;
    uint16_t crc;
    uint8_t  raw[13];              /* mode, STX, flight[7], label[2], bid, STX */
    char     buf[ACR_MSGMAX];      /* the message text field                   */
} dem_t;

/* ---- app state ---- */
static struct {
    const app_api_t *A;
    char   *text;                  /* formatting buffer (app_main's stack)     */
    char   *msg;                   /* current message text (app_main's stack)  */
    char    flt[8], lbl[3], bid;
    uint8_t mlen, top, prevKey, redraw, ledPhase, busyFor;
    uint16_t count;
    uint16_t nSyn, nSyn2, nHdr, nCrcErr, nBytes; /* debug counters (WAIT screen) */
    int32_t  level;                 /* last matched-filter magnitude          */
    uint8_t  badcrc;                /* shown frame failed its CRC             */
    uint8_t  trace[8], traceN;      /* bytes following the last detected SYN  */
    uint8_t  afIdx;                 /* AF output-mode cycle index (key 2)     */
    bool    running, spk, blAlways;
    int32_t rssi;
    uint32_t tPrev, tCyc, rssiMs;
    uint32_t savedSqr3, savedSmpr3;
} g;
#define str g.text

/* ---- tiny freestanding helpers ---- */
void *memset(void *d, int c, size_t n){ uint8_t *p=d; while(n) p[--n]=(uint8_t)c; return d; }

static char *put(char *o,const char *s){ while(*s)*o++=*s++; return o; }
static unsigned sub(uint32_t *v,uint32_t d){ unsigned q=0; while(*v>=d){ *v-=d; q++; } return q; }
static const uint32_t P10U[]={1000000u,100000u,10000u,1000u,100u,10u,1u};
static char *putu(char *o,uint32_t v){
    bool lead=false;
    for(uint8_t i=0;i<7u;i++){
        unsigned c=sub(&v,P10U[i]);
        if(c||lead||i==6u){ *o++=(char)('0'+c); lead=true; }
    }
    return o;
}
static char *putx2(char *o,uint8_t v){
    const char *H="0123456789ABCDEF";
    *o++=H[(v>>4)&0xFu]; *o++=H[v&0xFu];
    return o;
}
/* printable ASCII, controls (CR/LF and the odd-parity leftovers) blanked */
static char pch(uint8_t v){
    char c=(char)(v&0x7Fu);
    return (c<0x20u||c>0x7Eu)?' ':c;
}

#define ROWY(i) ((uint8_t)((i)*8u))

/* ---- PA4 bias (AC-coupled audio needs a mid-scale reference; EPIRB 406) ---- */
static void biasOn(uint32_t moder,uint32_t rcc){
    GPIOA_MODER=moder|(3u<<8);
    RCC_APBENR1=rcc|RCC_DACEN;
    DAC_CR=DAC_CR_BIAS;
    DAC_DHR12R1=BIAS_CODE;
    DAC_SWTRIGR=1u;
}
static void biasOff(uint32_t dac,uint32_t dhr,uint32_t rcc,uint32_t moder){
    DAC_CR=dac; DAC_DHR12R1=dhr; RCC_APBENR1=rcc; GPIOA_MODER=moder;
}
static void adcSelPA4(void){
    ADC_SMPR3=(g.savedSmpr3&~(7u<<SMP4_POS))|(((g.savedSmpr3>>SMP8_POS)&7u)<<SMP4_POS);
    ADC_SQR3=(g.savedSqr3&~0x1Fu)|ADC_CH_PA4;
}
static void adcRestore(void){ ADC_SQR3=g.savedSqr3; ADC_SMPR3=g.savedSmpr3; }
static uint16_t adcRead(void){
    ADC_CR2|=ADC_CR2_START;
    for(uint16_t n=0; !(ADC_SR&ADC_SR_EOC) && n<2000u; n++){}
    return (uint16_t)(ADC_DR&0x0FFFu);
}

/* ---- SysTick cycle counter (call at least every 10 ms) ---- */
static void clkStart(void){ g.tPrev=SYST_VAL; g.tCyc=0; }
static uint32_t clkCyc(void){
    uint32_t v=SYST_VAL;
    g.tCyc += (v<=g.tPrev) ? g.tPrev-v : g.tPrev+(SYST_LOAD+1u-v);
    g.tPrev=v;
    return g.tCyc;
}

/* ---- CRC-16/KERMIT, reflected 0x8408, init 0 (acarsdec update_crc) ---- */
static uint16_t crcu(uint16_t crc,uint8_t c){
    crc^=c;
    for(uint8_t i=0;i<8u;i++) crc=(uint16_t)((crc&1u)?((crc>>1)^0x8408u):(crc>>1));
    return crc;
}

/* ---- a frame: copy what the screen needs (crcok=0: shown flagged) ---- */
static void acr_emit(const dem_t *m,uint8_t crcok){
    g.count++;
    g.badcrc=(uint8_t)(crcok?0u:1u);
    uint8_t n=m->tlen;
    if(n==0u) return;                       /* no text: keep what is shown */
    char *o=g.msg;
    for(uint8_t i=0;i<n;i++) *o++=pch((uint8_t)m->buf[i]);
    while(o>g.msg && o[-1]==' ') o--;       /* trim trailing blanks */
    *o='\0';
    g.mlen=(uint8_t)(o-g.msg);
    for(uint8_t i=0;i<7u;i++) g.flt[i]=pch(m->raw[2u+i]);
    g.flt[7]='\0';
    for(uint8_t i=0;i<2u;i++) g.lbl[i]=pch(m->raw[9u+i]);
    g.lbl[2]='\0';
    g.bid=pch(m->raw[11]);
    g.top=0u;
    g.redraw=1u;
    g.A->backlight_on();                    /* wake the screen on a decode */
    g.ledPhase=4u;                          /* green LED: on/off/on/off */
}

/* ---- frame state machine (acarsdec decodeAcars, without the inv attribute:
 * the polarity is folded into the demodulator through msks ^= 2) ---- */
static void acr_byte(dem_t *m,uint8_t r){
    if(m->st!=0u) g.nBytes++;               /* a real byte boundary, not a slide */
    switch(m->st){
    case 0u:                                /* WSYN, sliding */
        if(r==0x16u){ g.nSyn++; m->st=1u; m->n=8u; }
        else if(r==0xE9u){ g.nSyn++; m->msks^=2u; m->st=1u; m->n=8u; }
        else m->n=1u;
        return;
    case 1u:                                /* SYN2 */
        if(r==0x16u){ m->st=2u; m->n=8u; }
        else { m->st=0u; m->n=1u; }
        return;
    case 2u:                                /* SOH1 */
        if(r==0x01u){ m->st=3u; m->n=8u; m->crc=0u; m->len=0u; m->tlen=0u; g.nHdr++; }
        else { m->st=0u; m->n=1u; }
        return;
    case 3u:                                /* TXT */
        if(m->len<13u){ if(m->len<sizeof m->raw) m->raw[m->len]=r; }
        else if(m->tlen<ACR_MSGMAX) m->buf[m->tlen++]=r;
        m->crc=crcu(m->crc,r);
        m->len++;
        if(r==0x83u||r==0x97u){ m->st=4u; m->n=8u; }
        else if(m->len>=240u){ m->st=0u; m->n=1u; }    /* runaway frame */
        else m->n=8u;
        return;
    case 4u:                                /* CRC1 */
        m->c0=r; m->crc=crcu(m->crc,r); m->st=5u; m->n=8u;
        return;
    default:                                /* CRC2 */
        m->crc=crcu(m->crc,r);
        if(m->len>=13u){
            if(m->crc==0u) acr_emit(m,1u);
            /* Lowered bar (debug): once SYN SYN SOH ... ETX got through, show
             * the frame even with a failed CRC, flagged '!', instead of dropping
             * it. Nothing reaches here without a full header, so false hits are
             * still rare. */
            else { g.nCrcErr++; if(m->tlen>0u) acr_emit(m,0u); }
        }
        m->st=0u; m->n=1u;
        return;
    }
}

/* ---- assembled bit -> byte -> frame ---- */
static void acr_putbit(dem_t *m,uint8_t b){
    m->ob=(uint8_t)(m->ob>>1);
    if(b) m->ob|=0x80u;
    if(--m->n==0u) acr_byte(m,m->ob);
}

/* ---- one ADC sample through the demodulator (FxDemod.push) ---- */
static void dem_sample(dem_t *m,int32_t x){
    const int32_t step=(int32_t)ACR_STEP + m->corr;
    m->acc=(m->acc+step)&4095;
    /* Round to nearest: a plain arithmetic >>8 floors, so every small negative
     * deviation drags the carrier level down and it never comes back up (the
     * exact bug EPIRB 406 hit at the PA4 levels). */
    { const int32_t e=x-m->dc; m->dc+=(e+(1<<(ACR_DCSH-1)))>>ACR_DCSH; }
    const int32_t y=x-m->dc;
    const uint32_t i=((uint32_t)m->acc>>6)&63u;
    const int32_t r=(y*ACR_T[i])>>12;                 /*  cos(p) * x */
    const int32_t q=(y*ACR_T[(i+16u)&63u])>>12;       /* -sin(p) * x */
    m->ring[2u*m->idx]=(int16_t)r;
    m->ring[2u*m->idx+1u]=(int16_t)q;
    if(++m->idx>=ACR_FLEN) m->idx=0u;

    m->clk+=step;
    if(m->clk<=(int32_t)ACR_CLKTHR) return;
    m->clk-=(int32_t)ACR_CLKTHR;

    /* matched filter over the last ACR_FLEN baseband samples, oldest first */
    int32_t vr=0, vi=0;
    uint8_t k=m->idx;
    for(uint8_t j=0;j<ACR_FLEN;j++){
        const int32_t hv=ACR_T[((uint32_t)(2*(int)j-16))&63u];
        vr+=hv*m->ring[2u*k];
        vi+=hv*m->ring[2u*k+1u];
        if(++k>=ACR_FLEN) k=0u;
    }

    g.level=(int32_t)(((vr<0?-vr:vr)+(vi<0?-vi:vi))>>16);   /* debug */

    /* MSK decision: alternating quadrature, sign only; the quadrature
     * component drives the carrier loop */
    int32_t dphi;
    switch(m->msks&3u){
    case 0u: acr_putbit(m,(uint8_t)(vr>0)); dphi=(vr>=0)?vi:-vi; break;
    case 1u: acr_putbit(m,(uint8_t)(vi>0)); dphi=(vi>=0)?-vr:vr; break;
    case 2u: acr_putbit(m,(uint8_t)(vr<0)); dphi=(vr>=0)?vi:-vi; break;
    default: acr_putbit(m,(uint8_t)(vi<0)); dphi=(vi>=0)?-vr:vr; break;
    }
    m->msks++;
    m->corr=(int8_t)((dphi>0)?ACR_PLLMAX:((dphi<0)?-ACR_PLLMAX:0));
}

/* ---- bottom status bar: key state, message count, live RSSI ---- */
static void drawFooter(const char *s){
    char *o=str;
    o=put(o,s+T_SPK); *o++=' '; o=put(o,g.spk?s+T_ON:s+T_OFF); *o++=' ';
    o=put(o,s+T_BL);  *o++=' '; o=put(o,g.blAlways?s+T_ON:s+T_OFF); *o++=' ';
    o=putu(o,g.count); *o++=' ';
    int32_t r=g.rssi;
    if(r<0){ *o++='-'; r=-r; }
    o=putu(o,(uint32_t)r);
    *o='\0';
    g.A->print_tiny(str,0,ROWY(6),false,true);
}

#define TXTCOLS 32u            /* 3x5 font, 4 px advance -> 128 px / 32 chars */
#define TXTROWS 5u             /* display rows 1..5 */

__attribute__((noinline))
static void draw(void){
    const app_api_t *A=g.A;
    char s[UI_SIZE] __attribute__((aligned(4)));
    A->asset_read(0,s,UI_SIZE);
    A->display_clear();
    A->status_clear();
    A->print_inverse(s+T_TITLE,2,0,true,true,(uint8_t)(2u+T_TITLE_CHARS*4u));
    A->draw_battery();

    if(g.count==0u){
        /* Bring-up debug, waiting: where the pipeline stops. Read the trace
         * line first - after a detected SYN it shows the next 8 raw bytes: a
         * real frame reads 16 01 <mode> 02 .., noise reads something random.
         * AF = current output mode (key 2 cycles it),
         * SYN = header starts, S2 = a 2nd SYN, HDR = SYN SYN SOH, BY = bytes
         * after a SYN, CE = CRC fails, LV = matched-filter magnitude. */
        char *o=str;
        o=put(o,"AF"); o=putu(o,AF_CYCLE[g.afIdx]); *o='\0';
        A->print_tiny(str,0,ROWY(0),false,true);
        o=str; *o++='T';
        for(uint8_t i=0;i<g.traceN;i++){ *o++=' '; o=putx2(o,g.trace[i]); }
        *o='\0';
        A->print_tiny(str,0,ROWY(1),false,true);
        A->print_tiny(s+T_WAIT,0,ROWY(2),false,true);
        o=str;
        o=put(o,"SYN"); o=putu(o,g.nSyn); o=put(o," S2"); o=putu(o,g.nSyn2);
        o=put(o," HDR"); o=putu(o,g.nHdr); *o='\0';
        A->print_tiny(str,0,ROWY(3),false,true);
        o=str; o=put(o,"BY"); o=putu(o,g.nBytes); o=put(o," CE"); o=putu(o,g.nCrcErr); *o='\0';
        A->print_tiny(str,0,ROWY(4),false,true);
        o=str; o=put(o,"LV"); o=putu(o,(uint32_t)(g.level<0?-g.level:g.level)); *o='\0';
        A->print_tiny(str,0,ROWY(5),false,true);
    } else {
        char *o=str;
        o=put(o,g.flt); *o++=' '; o=put(o,g.lbl); *o++=' '; *o++=g.bid;
        if(g.badcrc) *o++='!';        /* frame shown without a valid CRC */
        *o='\0';
        A->print_bold(str,0,0,0);
        for(uint8_t row=0;row<TXTROWS;row++){
            uint16_t off=(uint16_t)g.top+(uint16_t)row*TXTCOLS;
            if(off>=g.mlen) break;
            uint8_t n=(uint8_t)(g.mlen-off);
            if(n>TXTCOLS) n=(uint8_t)TXTCOLS;
            for(uint8_t i=0;i<n;i++) str[i]=g.msg[off+i];
            str[n]='\0';
            A->print_tiny(str,0,ROWY((uint8_t)(row+1u)),false,true);
        }
    }
    drawFooter(s);

    /* Frequency on the status bar (the framebuffer is only 7 rows tall, so a
     * y >= 56 would write past gFrameBuffer). */
    char *f=str; uint32_t fr=A->rx_freq();
    f=putu(f,sub(&fr,100000u)); *f++='.';
    *f++=(char)('0'+sub(&fr,10000u)); *f++=(char)('0'+sub(&fr,1000u));
    *f++=(char)('0'+sub(&fr,100u)); *f++=(char)('0'+sub(&fr,10u));
    *f='\0';
    A->print_tiny(str,46,0,true,true);

    A->blit_status();
    A->blit_full();
}

/* ---- input ---- */
static void handleKeys(void){
    const app_api_t *A=g.A;
    const uint8_t key=A->get_key();
    /* One step per press: acting on the raw held key every house slot would
     * auto-repeat at ~20/s. */
    if(key==APP_KEY_INVALID||key==g.prevKey){ g.prevKey=key; return; }
    g.prevKey=key;
    const int d=A->nav_dir(key);
    if(d){
        if(g.count){
            const uint16_t lines=((uint16_t)g.mlen+TXTCOLS-1u)/TXTCOLS;
            const uint16_t maxl=(lines>TXTROWS)?(uint16_t)(lines-TXTROWS):0u;
            int t=(int)(g.top/TXTCOLS)+d;
            if(t<0) t=0;
            if(t>(int)maxl) t=(int)maxl;
            if((uint8_t)(t*TXTCOLS)!=g.top){ g.top=(uint8_t)(t*TXTCOLS); g.redraw=1u; }
        }
        return;
    }
    g.redraw=1u;
    switch(key){
        case APP_KEY_EXIT: g.running=false; break;
        case APP_KEY_1:    g.spk=!g.spk; A->audio_path(g.spk); break;
        case APP_KEY_2:    /* bring-up: cycle the AF output mode, watch the trace */
                           g.afIdx=(uint8_t)((g.afIdx+1u)%AF_CYCLE_N);
                           A->set_af(AF_CYCLE[g.afIdx]);
                           break;
        case APP_KEY_3:    /* back to the WAIT debug screen (clear everything) */
                           g.count=0u; g.mlen=0u; g.top=0u;
                           g.nSyn=g.nSyn2=g.nHdr=g.nCrcErr=g.nBytes=0u;
                           g.traceN=0u;
                           break;
        case APP_KEY_4:    g.blAlways=!g.blAlways;
                           A->backlight_on();   /* re-arm; house() holds it on when ON */
                           break;
        default: break;
    }
}

/* ---- keys and screen, between frames ---- */
static void house(void){
    const app_api_t *A=g.A;
    handleKeys();
    if(!g.running) return;
    g.rssi=A->rssi_dbm();
    const uint32_t now=A->ticks_ms();
    if((uint32_t)(now-g.rssiMs)>=500u){ g.rssiMs=now; g.redraw=1u; }  /* RSSI every 0.5 s */
    if(g.blAlways) A->backlight_on();   /* re-arm BLTime every slot so it never expires */
    /* The fade only advances inside BACKLIGHT_Update(), which this service
     * drives: without it a dark panel would never light up after key 4 or a
     * decode wake-up (TurnOn just sets the target brightness). */
    A->backlight_update();
    if(!g.redraw) return;
    g.redraw=0;
    adcRestore();
    A->battery_sample();
    adcSelPA4();
    draw();
}

__attribute__((noinline))
static void listen(void){
    dem_t dm;                       /* on the stack: .bss counts toward the 4 KiB */
    memset(&dm,0,sizeof dm);
    dm.n=8u;                        /* the byte assembler starts on a boundary */

    adcSelPA4();
    clkStart();
    uint32_t next=0;
    uint16_t cnt=0;
    uint16_t ledCnt=0;
    g.redraw=1u;
    while(g.running){
        while((int32_t)(clkCyc()-next)<0){}
        next+=CYC_PER_SAMPLE;
        dem_sample(&dm,adcRead());
        /* Green-LED double-blink: one step every 1920 samples (100 ms), i.e.
         * on 100 / off 100 / on 100 / off 100 - the same 100 ms "on" width the
         * radio's own A/B (RX-end) blink uses. The BK4819 GPIO6 write costs
         * ~40 us (< one sample period), so the sampler is not disturbed. */
        if(++ledCnt>=LED_EVERY){ ledCnt=0; if(g.ledPhase){ g.A->led((g.ledPhase&1u)==0u); g.ledPhase--; } }
        if(++cnt<HOUSE_EVERY) continue;
        cnt=0;
        /* keep sampling while a frame is being received (or for at most 5 s) */
        if(dm.st!=0u && ++g.busyFor<BUSY_MAX) continue;
        g.busyFor=0;
        house();
        next=clkCyc();
        if(!g.running) break;
    }
    adcRestore();
}

__attribute__((section(".text.entry"),used))
void app_main(const app_api_t *api){
    char text[48];
    char msg[ACR_MSGMAX];
    g.A=api;
    g.text=text;
    g.msg=msg;
    g.flt[0]=g.lbl[0]=g.bid='\0';
    g.prevKey=APP_KEY_INVALID;
    msg[0]='\0';
    g.savedSqr3=ADC_SQR3; g.savedSmpr3=ADC_SMPR3;
    const uint32_t savedModer=GPIOA_MODER, savedDac=DAC_CR;
    const uint32_t savedRcc=RCC_APBENR1, savedDhr=DAC_DHR12R1;
    biasOn(savedModer,savedRcc);
    api->backlight_on();

    uint8_t cfg=0;
    api->cfg_load(&cfg,1);
    g.spk=(cfg&1u)!=0u;

    /* RAW RX: HPF/LPF, de-emphasis and AFC off (EPIRB 406); AM for the ACARS
     * subcarrier. The loader restores the registers on exit.
     *
     * AF output mode: FM (1) by default, like the radio's own AM path
     * (RADIO_SetModulation: "AM no longer needs special AF setting", REG_47 =
     * 0x6140) and like the LBJ/APRS/EPIRB apps; AF_AM (7) writes 0x6740, which
     * this firmware uses nowhere else. v0.1 was stuck on AF_AM and never
     * decoded, so v0.2 starts on FM and lets key 2 cycle FM/AM/RAW/USB while
     * the trace line shows which one yields a real 16 01 (see README). */
    api->bk_write(REG_2B,(uint16_t)((api->bk_read(REG_2B)|0x0700u)&~0x0007u));
    api->bk_write(REG_73,(uint16_t)(api->bk_read(REG_73)|0x0010u));
    api->audio_path(g.spk);
    g.afIdx=0u;                    /* AF_CYCLE[0] = FM, the radio's own AM path */
    api->set_af(AF_CYCLE[g.afIdx]);
    api->delay_ms(50);

    g.running=true;
    listen();

    biasOff(savedDac,savedDhr,savedRcc,savedModer);
    api->led(false);           /* do not leave the green LED stuck mid-blink */
    api->set_af(APP_AF_MUTE);
    api->audio_path(false);
    cfg=(uint8_t)(g.spk?1u:0u);
    api->cfg_save(&cfg,1);
}
